device-types/Arista/DCS-7020SR-24C2-F.yaml, device-types/Arista/DCS-7020SR-24C2-R.yaml
- Added folder for vendor: Arista
- Added device templates for two 7020 switches
=> Add vendor: Arista | Add switch model: 7020

device-types/Arista/DCS-7050CX3-32S-F.yaml, device-types/Arista/DCS-7050CX3-32S-R.yaml
Added Arista: DCS-7050CX3-32-(F/R)
=> added two model 7050 switches

device-types/Arista/DCS-7010T-48-F.yaml, device-types/Arista/DCS-7010T-48-R.yaml, device-types/Arista/DCS-7050SX3-48YC12-F.yaml, device-types/Arista/DCS-7050SX3-48YC12-R.yaml, device-types/Arista/DCS-7050SX3-48YC8-F.yaml, device-types/Arista/DCS-7050SX3-48YC8-R.yaml, device-types/Arista/DCS-7280SR2-48YC6-F.yaml, device-types/Arista/DCS-7280SR2-48YC6-R.yaml
**Arista Models Added:**
- DCS-7050SX3-48YC12-*
- DCS-7050SX3-48YC8-*
- DCS-7010T-48-*
=> Arista Additions

device-types/Arista/DCS-7150S-24-F.yaml, device-types/Arista/DCS-7150S-24-R.yaml, device-types/Arista/DCS-7150S-52-F.yaml, device-types/Arista/DCS-7150S-52-R.yaml, device-types/Arista/DCS-7150S-64-F.yaml, device-types/Arista/DCS-7150S-64-R.yaml, device-types/Arista/DCS-7150SC-24-F.yaml, device-types/Arista/DCS-7150SC-24-R.yaml, device-types/Arista/DCS-7150SC-64-F.yaml, device-types/Arista/DCS-7150SC-64-R.yaml
=> Entire Arista 7150 Series

device-types/Arista/DCS-7050TX3-48C8-F.yaml, device-types/Arista/DCS-7050TX3-48C8-R.yaml
Closes out the Arista 7050X3 series.
=> Arista 7050TX3

device-types/Cisco/N5K-C5548UP.yaml, device-types/Juniper/SRX240H2.yaml
=> Juniper srx

device-types/Juniper/SRX345.yaml, device-types/Lenovo/FLEX-SYSTEM.yaml, device-types/Lenovo/SR630.yaml
added a firewall, server and a blade chassis.
=> Added multiple devices

device-types/Cisco/ws-2960cg-8tl.yaml
Added Cisco WS-2960CG-8TL device type
=> Cisco WS-2960CG-8TL

device-types/Juniper/EX3400-24P.yaml, device-types/Juniper/EX3400-24T.yaml, device-types/Juniper/EX3400-48P.yaml, device-types/Juniper/EX3400-48T.yaml, device-types/Juniper/EX4300-24P.yaml
Added:
* EX3400-24P
* EX3400-24T
* EX3400-48P
* EX3400-48T
=> Added ex3400 varients

.gitignore, device-types/Fortinet/FG-100F.yaml, device-types/Fortinet/FG-101F.yaml, device-types/Fortinet/FG-1100E.yaml, device-types/Fortinet/FG-1101E.yaml, device-types/Fortinet/FG-300E.yaml, device-types/Fortinet/FG-301E.yaml, device-types/Fortinet/FG-600E.yaml, device-types/Fortinet/FG-601E.yaml, device-types/Infoblox/TE-805-HW-AC-B.yaml, device-types/Juniper/SRX340.yaml, device-types/Opengear/CM7116-2-DAC-US.yaml, device-types/Opengear/CM7116-2-SAC-US.yaml, device-types/Opengear/CM7132-2-DAC.yaml, device-types/Opengear/CM7148-2-DAC-US.yaml, device-types/Opengear/CM7148-2-SAC-US.yaml, device-types/Opengear/CM7196-2-DAC-US.yaml
- Fortinet Fortigate Additions
- Infoblox physical TE-805 Appliance
- Juniper SRX 340
- Opengear CM7100 Series
=> Various Devices

device-types/Juniper/SRX4600.yaml
=> added juniper srx4600 device

device-types/Cisco/c9300-48uxm.yaml, device-types/Juniper/SRX4600.yaml
Model added:
Cisco C9300-48UXM
=> Cisco c9300uxm

device-types/Juniper/EX3400-48T.yaml
This fixed issue #57.
Change model and slug.
=> Fix model and slug

device-types/Cisco/ws-c3560-48ps.yaml, device-types/Cisco/ws-c3560v2-24ps.yaml, device-types/Cisco/ws-c3560v2-48ps.yaml, device-types/Cisco/ws-c3560x-24p.yaml, device-types/Cisco/ws-c3560x-48p.yaml, device-types/Cisco/ws-c3650-24ps.yaml, device-types/Cisco/ws-c3650-24ts.yaml, device-types/Cisco/ws-c3650-48ps.yaml, device-types/Cisco/ws-c3750g-12s.yaml, device-types/Cisco/ws-c3750x-12s.yaml, device-types/Cisco/ws-c3750x-24.yaml, device-types/Cisco/ws-c3850-12s.yaml, device-types/Cisco/ws-c3850-12xs.yaml, device-types/Cisco/ws-c3850-24s.yaml, device-types/Cisco/ws-c3850-24u.yaml, device-types/Cisco/ws-c3850-24xs.yaml, device-types/Cisco/ws-c3850-48p.yaml, device-types/Cisco/ws-c3850-48u.yaml
Information taken from real switches as well as comparing/checking with datasheets.
=> Adding a lot of Cisco Catalyst WS-C3K

device-types/APC/AP7830.yaml, device-types/APC/AP8868.yaml, device-types/APC/AP8886.yaml, device-types/APC/AP8932.yaml
- Added comments
- Added part_numbers
- Added is_full_depth
- Corrected power-outlet names
=> update APC PDUs

device-types/APC/AP8853.yaml, device-types/Cisco/DN2-HW-APL.yaml
Addition to Cisco DNA Centre Gen2 44 Core appliance and APC PDU, first of 30 device types to be created as being used in the Smart Mobility Living Lab.
=> Smll cisco devices

device-types/Dell/PowerConnect_6224.yaml, device-types/Dell/PowerConnect_6248.yaml
Added Dell PowerConnect 6224 & 6248
=> Added Dell PowerConnect 62xx

device-types/Arista/DCS-7124SX.yaml, device-types/Avocent/Cyclades-TS1000.yaml, device-types/Cisco/CS-500.yaml, device-types/CyberPower/OR2200LCDRT2U.yaml
Cisco CS-500
Avocent Cyclades TS1000
Arista 7124SX
Cyberpower OR2200LCDRT2U UPS
=> Add multiple devices from my homelab

device-types/Ubiquiti/usg-pro-4.yaml
Definition for Ubiquiti’s USG-PRO-4 router.
=> Add Ubiquiti USG-PRO-4

device-types/Cisco/ws-c2960c-12pc-l.yaml
Hi, adding another Cisco switch. Datasheet here : https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-2960-c-series-switches/data_sheet_c78-639705.html.
=> add ws-c2960c-12pc-l.yaml

device-types/APC/AP8865.yaml
=> Add AP8865

device-types/Cisco/ISR4321.yaml
=> added definition for ISR4321

device-types/WTI/CPM-1600-1-ECAM.yaml, device-types/WTI/CPM-800-1-A-VZW.yaml, device-types/WTI/CPM-800-1-A.yaml, device-types/WTI/CPM-800-1-AM.yaml, device-types/WTI/CPM-800-1-E.yaml, device-types/WTI/CPM-800-1-EA.yaml, device-types/WTI/CPM-800-2-A-VZW.yaml, device-types/WTI/CPM-800-2-A.yaml, device-types/WTI/CPM-800-2-AM.yaml, device-types/WTI/CPM-800-2-E.yaml, device-types/WTI/CPM-800-2-EA.yaml
These are the device definition types for WTI's combo OOB and Power devices.
=> Added popular WTI devices CPM (Console Server + Power Control Combos)

device-types/WTI/VMR-16HD20-2.yaml, device-types/WTI/VMR-8H20-ATS-1.yaml, device-types/WTI/VMR-8H20-ATS-2.yaml, device-types/WTI/VMR-8HS20-1.yaml, device-types/WTI/VMR-8HS20-2.yaml
These are the device definition types for WTI's VMR PDU devices.
=> added popular WTI Power VMR devices (Outlet PDU devices)

device-types/Fortinet/FG-100E.yaml, device-types/Fortinet/FG-3000D.yaml
Added 2 devicetypes for Fortinet:
- 3000D 
- 100E
=> Creation of FG-3000D and FG-100E

device-types/Cisco/AIR-CT5520-K9.yaml
=> Creation of Cisco WLC 5520

device-types/Cisco/ws-c4900m.yaml
This adds the chassis of the Cisco Catalyst 4900M switches.
=> Add Cisco WS-C4900M switch

device-types/HPE/HPE-SY480.yaml, device-types/HPE/c7000.yaml, device-types/HPE/synergy-12000.yaml
Added in the folder HPE several device-types:
- c7000.yaml
- HPE-SY480.yaml
- synergy-12000.yaml
Which include a chassis/blade (parent/child)
=> Creation of HPE folder and added 3 device-types

device-types/Dell/networking-s5232f-on.yaml
Support Dell networking S5232F-ON platform
=> Support Dell networking S5232F-ON platform

device-types/Arista/DCS-7048T-A.yaml, device-types/Arista/DCS-7050S-52.yaml, device-types/Arista/DCS-7050S-64.yaml, device-types/Cisco/ME-3750-24TE-M.yaml, device-types/Juniper/EX4500-40F.yaml, device-types/Juniper/MX80.yaml
add yaml for Arista 7048T-A 
add yaml for Arista 7050S-52 
add yaml for Arista 7050S-64
=> added one 7048 and two 7050 model switches

device-types/Opengear/CM7196-2-DAC-US.yaml, device-types/Opengear/IM7216-2-DAC-US.yaml, device-types/Opengear/IM7232-2-DAC-US.yaml
Added IM7216-2-DAC-US and IM7232-2-DAC-US.
Adjusted power draw for some existing Opengear device types based on details found in technical specifications
=> Add Opengear IM7216 and IM7232 and tweak power on existing models

device-types/Ubiquiti/es-16-150w.yaml, device-types/Ubiquiti/es-16-xg.yaml, device-types/Ubiquiti/es-24-250w.yaml, device-types/Ubiquiti/es-24-500w.yaml, device-types/Ubiquiti/es-24-lite.yaml, device-types/Ubiquiti/es-48-500w.yaml, device-types/Ubiquiti/es-48-750w.yaml, device-types/Ubiquiti/es-48-lite.yaml
ES-48-LITE
ES-48-750W
ES-48-500W
ES-24-LITE
ES-24-500W
ES-24-250W
ES-16-150W
ES-16-XG
=> Add several Ubiqui EdgeSwitch

device-types/Fortinet/FWB-2000E.yaml
with optional bypass mode emulation for ports 1-4
=> Add Fortinet FWB-2000E

device-types/Extreme/BR-SLX-9540-48S-AC.yaml
PR to add Extreme's SLX9540-48S platform
=> add Extreme SLX9540

device-types/TrendNet/TEG-S224.yaml, device-types/TrippLite/ULTRABLOK428.yaml
=> Add TrendNet TEG-S224 switch and TrippLite UltraBlok surge device

device-types/Arista/DCS-7280TR-48C6.yaml
Added Arista DCS-7280TR-48C6 device.
=> Added Arista DCS-7280TR-48C6 device

AIR-CT5508-K9.yaml, N5K-C5648Q.yaml
Added one new Nexus device type and one new Wireless Controller device type to the Cisco library
=> Added Nexus 5648 and AIR 5508

device-types/Juniper/SRX-1500.yaml, device-types/Opengear/IM7248-2-DAC-US.yaml
added srx-1500 to device library.  Used the 2 PSUs variant as the logic is that its easier to remove stuff than it is to add.
=> added SRX-1500 to device library

device-types/Juniper/EX4500-40F.yaml
=> Updated EX4500-40F part number

device-types/Cisco/WS-C3560-48TS-S.yaml
=> fixed model/slug/part_number/interfaces

device-types/Cisco/WS-C3560-24TS-S.yaml, device-types/Cisco/WS-C3560-48PS-E.yaml, device-types/Cisco/WS-C3560-48PS-S.yaml, device-types/Cisco/WS-C3560G-48PS-S.yaml, device-types/Cisco/WS-C3560G-48TS-S.yaml, device-types/Cisco/WS-C3560V2-24TS-S.yaml, device-types/Cisco/WS-C3560V2-48PS-S.yaml, device-types/Cisco/WS-C3560V2-48TS-S.yaml, device-types/Cisco/WS-C3560X-48P-S.yaml
Nine templates added, none should conflict with #203
=> Added nine c3560 models

device-types/Cisco/C9200-24P.yaml, device-types/Cisco/C9200-24T.yaml, device-types/Cisco/C9200-48P.yaml, device-types/Cisco/C9200-48T.yaml, device-types/Cisco/C9200L-24P-4G.yaml, device-types/Cisco/C9200L-24P-4X.yaml, device-types/Cisco/C9200L-24T-4G.yaml, device-types/Cisco/C9200L-24T-4X.yaml, device-types/Cisco/C9200L-48P-4G.yaml, device-types/Cisco/C9200L-48P-4X.yaml, device-types/Cisco/C9200L-48T-4G.yaml, device-types/Cisco/C9200L-48T-4X.yaml
I prepared yaml files for:
C9200-24T, C9200-24P, C9200-48T, C9200-48P, C9200L-24T-4G, C9200L-24P-4G, C9200L-48T-4G, C9200L-48P-4G, C9200L-24T-4X, C9200L-24P-4X, C9200L-48T-4X, C9200L-48P-4X
=> Cisco Catalyst 9200 series switches

device-types/TP-Link/TL-SG1024D.yaml
https://www.tp-link.com/de/business-networking/unmanaged-switch/tl-sg1024d/
would be great if this PR gets tagged with "hacktoberfest-accepted"
=> Added the TP-Link TL-SG1024D

device-types/Fortinet/FG-60E.yaml
Added 1 devicetypes for Fortinet:
- 60E
=> Creation of Fortinet FortiGate 60E

device-types/APC/AP4431.yaml
Added APC AP4431 ATS to the device library
=> Add APC AP4431 ATS

device-types/Avocent/PM10-20A.yaml
Add an Avocent/Cyclades AlterPath PM10-20A PDU
=> Add Cyclades/Avocent AlterPath PM10

device-types/Palo Alto/PA-3050.yaml, device-types/Palo Alto/PA-3060.yaml, device-types/Palo Alto/PA-500.yaml, device-types/Palo Alto/PA-850.yaml
Add four Palo Alto models
- PA-3050
- PA-3060
- PA-850
- PA-500
=> Add Palo Alto 3050,3060, 500, and 850

device-types/Cisco/cdb-8p.yaml, device-types/Cisco/cdb-8u.yaml, device-types/Cisco/cdb-mnt-rack5-c14.yaml
These devices are a bit special. See the comments in the files.
Signed-off-by: Felix Kaechele <fkaechel@cisco.com>
=> Add Cisco Catalyst Digital Building Switch

device-types/Generic/shelf-2he.yaml, tests/test_dupes.py
Slug seemed to make the most sense to compare against, and doing that I found a duplicate Generic device.
First pytest I've ever written, open to feedback!
=> Per #175, check for duplicate devices

device-types/APC/AP8941.yaml
Another model of APC Rack installable PDU
=> Add APC AP8941 rack PDU

device-types/APC/AP9319.yaml
APC Environmental monitoring device running AOS like the UPS management cards
=> Add APC AP9319 environmental monitoring unit

device-types/Cisco/N9K-C93108LC-EX.yaml, device-types/Cisco/N9K-C93108TC-EX.yaml, device-types/Cisco/N9K-C9332PQ.yaml, device-types/Cisco/N9K-C9372TX.yaml
Add more Cisco Nexus 9k model types
=> Add Cisco Nexus 9k models

device-types/Cisco/AS2511RJ.yaml
Add Cisco older terminal server model
=> Add Cisco 2511 Terminal Server

device-types/Cisco/ASA5510.yaml, device-types/Cisco/ASA5550.yaml, device-types/Cisco/ASA5555.yaml, device-types/Cisco/ASA5585-SSP-20.yaml
Add some older Cisco ASA model types that weren't in the library.
=> Add older Cisco ASA models

device-types/Cisco/N3K-C3232C.yaml
Add Nexus 3k c3232c model
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-3232c-switch/datasheet-c78-734883.html
=> Add Nexus 3k 32-port qsfp28

device-types/Cisco/N5K-C5596T.yaml
Add another Cisco Nexus 5k model with 32 10GbaseT ports and 16 SFP+ ports
https://www.cisco.com/c/en/us/products/switches/nexus-5596t-switch/index.html
=> Add Cisco Nexus 5k C5596T

device-types/Cisco/WS-C6506-E.yaml, device-types/Cisco/WS-C6509-V-E.yaml, device-types/Cisco/WS-C6509.yaml, device-types/Cisco/WS-C6513.yaml
Add Cisco Catalyst 6k chassis variants
=> Add Cisco Catalyst 6k chassis variants

device-types/Palo Alto/M-100.yaml, device-types/Palo Alto/M-500.yaml, device-types/Palo Alto/PA-220.yaml, device-types/Palo Alto/PA-3020.yaml, device-types/Palo Alto/PA-5060.yaml, device-types/Palo Alto/PA-7080.yaml, device-types/Palo Alto/PA-820.yaml
Add Palo Alto management servers for Panorama and missing firewall models
Rename uplink interfaces on PA-5050
=> Add Palo Alto management servers and missing firewall models

device-types/Citrix/SDX-14000.yaml
Add NetScaler 14000 hardware device
=> Add Citrix Netscaler SDX 14000 family

device-types/Arista/DCS-7050SX-64.yaml, device-types/Arista/DCS-7050T-52.yaml, device-types/Arista/DCS-7050TX-72Q.yaml
Added a few Arista 7050s
- DCS-7050SQ-64
- DCS-7050T-52
- DCS-7050TX-72Q
=> Add a few Arista 7050s

device-types/Brocade/fws624g.yaml, device-types/Brocade/fws648g.yaml, device-types/Brocade/icx6610-24.yaml, device-types/Brocade/icx6610-48.yaml, device-types/Brocade/icx6610-48p.yaml
Add some older Brocade models
- FastIron WS 624G
- FastIron WS 648G
- ICX 6610-24
- ICX 6610-48
- ICX 6610-48P
=> Add Brocade models

device-types/Opengear/IM4216-2.yaml, device-types/Opengear/IM4232-2.yaml, device-types/Opengear/IM4248-2.yaml, device-types/Opengear/IM7248-2-DAC-LMA.yaml, device-types/Opengear/IM7248-2-DAC-LMP.yaml, device-types/Opengear/IM7248-2-DAC-LMV.yaml, device-types/Opengear/IM7248-2-DAC-LR.yaml, device-types/Opengear/IM7248-2-DAC.yaml
Add Opengear IM4216, IM4232, IM4248, and multiple IM7248 variants
=> Add multiple Opengear models

device-types/Palo Alto/PA-820.yaml
=> Fix typo in PA-820

device-types/Juniper/QFX5120-32C.yaml, device-types/Juniper/QFX5120-48T.yaml, device-types/Juniper/QFX5120-48Y.yaml, device-types/Juniper/QFX5130-32CD.yaml, device-types/Juniper/QFX5200-32C.yaml, device-types/Juniper/QFX5200-48Y.yaml, device-types/Juniper/QFX5210-128C.yaml, device-types/Juniper/QFX5210-64C.yaml
Added addition QFX Devices;
- QFX5120-32C
- QFX5120-48T
- QFX5120-48Y
- QFX5130-32CD
- QFX5200-32C
- QFX5200-48Y
- QFX5210-128C
- QFX5210-64C
=> added additional QFX5k series devices

device-types/Cisco/WS-C3650-48FD-L.yaml, device-types/Cisco/ws-c3650-48fd-e.yaml, device-types/Cisco/ws-c3650-48fd-s.yaml, device-types/Cisco/ws-c3650-48td-e.yaml
Add three variants of C3650
- ws-c3650-48fd-e
- ws-c3650-48fd-s
- ws-c3650-48td-e
Fixed typo in WS-C3650-48FD-L as well
=> Add three C3650 models

device-types/Cisco/N77-C7706.yaml, device-types/Cisco/N77-C7710.yaml
Add Cisco Nexus 77xx Chassis models.
=> Add Cisco Nexus 77xx family Chassis

device-types/Juniper/ACX5448-M.yaml, device-types/Juniper/ACX710-DC.yaml, device-types/Juniper/SRX380-P.yaml
=> Add new Juniper SRX and ACX models

device-types/Cisco/AS2511RJ.yaml
The line ports are actually console-server-ports....
=> change line to console-server-ports

device-types/Infinera/CloudXpress2.yml
Initial for Infinera DWDM Hardware
=> Added Infinera Cloud Xpress2

device-types/Cisco/C9500-16X.yaml
Add Cisco Catalyst 9500-16X. This is based off the Catalyst 9500-40X.
=> Add Catalyst 9500-16X

device-types/Cisco/cdb-8p.yaml, device-types/Cisco/cdb-8u.yaml
=> Catalyst digital building switch u height defect

device-types/ActionTec/C1000A.yaml, device-types/ActionTec/GT724R.yaml
There really is no good interface type for POTS so I added them as 100's.
=> Add two ActionTec DSL modems.

device-types/Arista/DCS-7280SR3-48YC8.yaml
=> Added Arista 7280sr3 48yc8

device-types/Cisco/C9200-48P.yaml, device-types/Juniper/QFX-5100-48S-3AFO.yaml
=> Fix inconsistent names reported in issue 327

device-types/Cisco/CBS350-24P-4G.yaml
Brand new Cisco small business switch
=> Cisco Business CBS350-24P-4G switch

device-types/Fortinet/FG-200F.yaml
=> Add files via upload - Fortinet FG-200F

device-types/Nokia/7210-SAS-Sx.yaml
add support for Nokia 7210 SAS series
=> Nokia 7210 sas

device-types/Cisco/C8500-12X.yaml, device-types/Cisco/C8500-12X4QC.yaml
Add the following Cisco C8500 routers
- C8500-12X
- C8500-12X4QC
=> Add Cisco C8500

device-types/Vertiv/ACS8008SAC.yaml, device-types/Vertiv/ACS8016DAC.yaml, device-types/Vertiv/ACS8016SAC.yaml, device-types/Vertiv/ACS8032SAC.yaml, device-types/Vertiv/ACS8048DAC.yaml, device-types/Vertiv/ACS8048SAC.yaml
Add the following Vertiv ACS 8000 console servers
- ACS8008SAC
- ACS8016DAC
- ACS8016SAC
- ACS8032SAC
- ACS8048DAC
- AVS8048SAC
=> Add Vertiv ACS8000

device-types/Fortinet/FG-600D.yaml
Add file for Fortinet Fortigate-600D
=> Fortinet fg600d

device-types/Adtran/MX2800.yaml, device-types/Riverbed/CX7055.yaml, device-types/Riverbed/CX755.yaml
Adding some more devices from Adtran and Riverbed.
=> Adtran and Riverbed devices

device-types/Fortinet/FG-200E.yaml, device-types/Fortinet/FG-201E.yaml
This PR adds Fortinet FG-200E and FG-201E. Series data sheet – https://www.fortinet.com/content/dam/fortinet/assets/data-sheets/FortiGate_200E_Series.pdf.
=> Add Fortinet FG-200E and FG-201E

device-types/MikroTik/RB1100AHx2.yaml
This PR adds MikroTik RB1100AHx2. Product page https://mikrotik.com/product/RB1100AHx2.
=> Add MikroTik RB1100AHx2

device-types/Ubiquiti/UNVR.yaml, device-types/Ubiquiti/USW-Aggregation.yaml
Added two Ubiquiti devices:
- UNVR from [datasheet](https://dl.ui.com/ds/unvr_ds.pdf)
- USW-Aggregation from [datasheet](https://dl.ubnt.com/ds/usw-aggregation-ds.pdf)
=> Add Ubiquiti UNVR and  USW-Aggregation

device-types/Cisco/Meraki-MS210-48LP.yaml
Meraki devices have no console ports
=> correct mgmt port type

device-types/MikroTik/CRS125-24G-1S-RM.yaml
Added new definition of CRS125-24G-1S, rackmount-Version
=> MikroTik CRS125-24G-1S-RM (Rackmount-Version)

device-types/Deciso/DEC2600.yaml, device-types/Deciso/DEC2610.yaml, device-types/Deciso/DEC2630.yaml, device-types/Deciso/DEC2640.yaml, device-types/Deciso/DEC2650.yaml, device-types/Deciso/DEC3840.yaml, device-types/Deciso/DEC3850.yaml, device-types/Deciso/DEC3860.yaml, device-types/Deciso/DEC4610.yaml, device-types/Deciso/DEC4620.yaml, device-types/Deciso/DEC4630.yaml, device-types/Deciso/DEC4640.yaml, device-types/Deciso/DEC600.yaml, device-types/Deciso/DEC610.yaml, device-types/Deciso/DEC620.yaml, device-types/Deciso/DEC630.yaml, device-types/Deciso/DEC670.yaml, device-types/Deciso/DEC690.yaml, device-types/Deciso/DEC840.yaml, device-types/Deciso/DEC850.yaml
Adding the official OPNsense appliances by Deciso
=> Deciso OPNsense appliances

device-types/APC/AP8959.yaml
Adds APC AP8959 PDU to the device library.
=> Add APC AP8959 PDU

device-types/APC/AP7921B.yaml, device-types/APC/AP7922B.yaml, device-types/APC/SRT5KRMXLI.yaml, device-types/APC/SRT5KRMXLT-IEC.yaml, device-types/APC/SRT5KRMXLT.yaml, device-types/APC/SRT5KRMXLW-HW.yaml, device-types/APC/SRT5KXLJ.yaml, device-types/APC/SRT6KRMXLI.yaml, device-types/APC/SRT8KRMXLT.yaml, device-types/Raritan/PX3-5469R.yaml
Add APC and Raritan UPS or PDUs.
=> Add new UPS and PDUs

device-types/Rockwell Automation/1783-BMS06SA.yaml, device-types/Rockwell Automation/1783-BMS06SGA.yaml, device-types/Rockwell Automation/1783-BMS06SGL.yaml, device-types/Rockwell Automation/1783-BMS06SL.yaml, device-types/Rockwell Automation/1783-BMS06TA.yaml, device-types/Rockwell Automation/1783-BMS06TGA.yaml, device-types/Rockwell Automation/1783-BMS06TGL.yaml, device-types/Rockwell Automation/1783-BMS06TL.yaml, device-types/Rockwell Automation/1783-BMS10CA.yaml, device-types/Rockwell Automation/1783-BMS10CGA.yaml, device-types/Rockwell Automation/1783-BMS10CGL.yaml, device-types/Rockwell Automation/1783-BMS10CGN.yaml, device-types/Rockwell Automation/1783-BMS10CGP.yaml, device-types/Rockwell Automation/1783-BMS10CL.yaml, device-types/Rockwell Automation/1783-BMS20CA.yaml, device-types/Rockwell Automation/1783-BMS20CGL.yaml, device-types/Rockwell Automation/1783-BMS20CGN.yaml, device-types/Rockwell Automation/1783-BMS20CGP.yaml, device-types/Rockwell Automation/1783-BMS20CGPK.yaml, device-types/Rockwell Automation/1783-BMS20CL.yaml, device-types/Rockwell Automation/1783-BMS4S2SGA.yaml, device-types/Rockwell Automation/1783-BMS4S2SGL.yaml
Added all variants of Rockwell Automation's Stratix 5700 industrial switch.
=> Add Rockwell Automation Stratix 5700

device-types/3Com/4200G-12_Port.yml, device-types/3Com/4200G-24_Port.yml, device-types/3Com/4200G-48_Port.yml, device-types/3Com/4200G-PWR-24_port.yml
This PR adds templates for 3Com 4200G family switches.
=> Add 3Com 4200G family switches

device-types/Palo Alto/PA-3250.yaml
=> Adding PA-3250

device-types/HPE/5800-24G(JC100B).yml, device-types/HPE/5800-48G(JC105B).yml, device-types/HPE/5820X-24XG-SFPP.yml, device-types/HPE/A5800-24G(JC100A).yml
This PR adds
* HPE A5800-24G
* HPE 5800-24G
* HPE 5800-48G
* HPE 5820X-24XG-SFPP
=> Add HPE A5800-24G, 5800-48G, 5820X-24XG-SFPP

device-types/Raspberry Pi/RPI4-MODBP-1GB.yaml
coorected rasberry pi 4 power-port
=> corrected raspberry pi power-port

device-types/3Com/4200G-12_Port.yml, device-types/3Com/4200G-24_Port.yml, device-types/3Com/4200G-48_Port.yml, device-types/3Com/4200G-PWR-24_port.yml, device-types/3Com/4210G-24_Port.yml, device-types/3Com/4210G-48_Port.yml, device-types/3Com/4210G-PWR-24_Port.yml, device-types/Cisco/SG350-10P-K9.yaml, device-types/Raritan/PX3TS-5184CR.yaml, device-types/Ubiquiti/UDM-Pro.yaml, device-types/cisco-ncs540-acc-sys.yaml
adding Raritan PX3TS-5184CR Rack Transfer Switchable PDU
=> Adding Raritan Switchable Transfer Switch device type

device-types/Juniper/SRX300.yaml
=> Adding SRX300 device

device-types/Arista/DCS-7060SX2-48YC6.yaml
See: https://www.arista.com/assets/data/pdf/Datasheets/7060X_7260X_DS.pdf
=> Add Arista model DCS-7060SX2-48YC6

device-types/CyberPower/CPS1215RMS.yaml, device-types/CyberPower/OR1000LCDRM1U.yaml
=> add cyberpower 1000va ups

device-types/Ubiquiti/UAP-AC-Lite.yaml, device-types/Ubiquiti/UAP-AC-M-Pro.yaml, device-types/Ubiquiti/UAP-AC-M.yaml, device-types/Ubiquiti/UAP-AC-Pro.yaml, device-types/Ubiquiti/UCK-G2-PLUS.yml, device-types/Ubiquiti/UCK-G2.yml
add wireless interfaces to UAP models, and cloud keys
=> update wireless interfaces

device-types/Ubiquiti/USW-Flex-Mini.yaml, device-types/Ubiquiti/USW-Flex.yaml
=> Add USW-Flex,USW-Flex-Mini

device-types/Rockwell Automation/1783-HMS16T4CGN.yaml, device-types/Rockwell Automation/1783-HMS16TG4CGN.yaml, device-types/Rockwell Automation/1783-HMS16TG4CGR.yaml, device-types/Rockwell Automation/1783-HMS4C4CGN.yaml, device-types/Rockwell Automation/1783-HMS4EG8CGN.yaml, device-types/Rockwell Automation/1783-HMS4EG8CGR.yaml, device-types/Rockwell Automation/1783-HMS4S8E4CGN.yaml, device-types/Rockwell Automation/1783-HMS4SG8EG4CGN.yaml, device-types/Rockwell Automation/1783-HMS4SG8EG4CGR.yaml, device-types/Rockwell Automation/1783-HMS4T4E4CGN.yaml, device-types/Rockwell Automation/1783-HMS8S4CGN.yaml, device-types/Rockwell Automation/1783-HMS8SG4CGN.yaml, device-types/Rockwell Automation/1783-HMS8SG4CGR.yaml, device-types/Rockwell Automation/1783-HMS8T4CGN.yaml, device-types/Rockwell Automation/1783-HMS8TG4CGN.yaml, device-types/Rockwell Automation/1783-HMS8TG4CGR.yaml, device-types/Rockwell Automation/1783-HMS8TG8EG4CGN.yaml, device-types/Rockwell Automation/1783-HMS8TG8EG4CGR.yaml
Adding Rockwell Automation's Stratix 5400 industrial switches (Cisco IE "private label")
=> Stratix 5400 switches

device-types/Arista/DCS-7368.yaml
See: https://www.arista.com/assets/data/pdf/Datasheets/7368X4-Datasheet.pdf
=> Add Arista DCS-7368

device-types/HPE/1810-24G(J9803A).yml, device-types/HPE/1820-48G(J9981A).yml, device-types/HPE/2620-24-PoEP(J9625A).yml
This PR adds device type templates for:
* HPE OfficeConnect 1810-24G
* HPE OfficeConnect 1820-24G
* HPE 2620 24 port PoE+
=> Add HPE access switches

device-types/Allied Telesis/AR1050V.yaml, device-types/Allied Telesis/AR2010V.yaml, device-types/Allied Telesis/AR2050V.yaml, device-types/Allied Telesis/AR3050S.yaml, device-types/Allied Telesis/AR4050S.yaml
Added Allied Telesis routers and UTMs (AR-series)
=> Added Allied Telesis AR-series

device-types/HPE/5800-24G(JC100B).yml, device-types/HPE/5800-48G(JC105B).yml, device-types/HPE/5820X-24XG-SFPP.yml, device-types/HPE/A5800-24G(JC100A).yml
* Add management interfaces
* Fix OBE in interface numbers
* Add missing 10GE interfaces that initially were considered as a module but are
actually fixed ones
* Add USB console ports
=> Fix the issues with HPE 5800/5820 series

device-types/Allied Telesis/GS980MX-10HSm.yaml, device-types/Allied Telesis/GS980MX-28.yaml, device-types/Allied Telesis/GS980MX-28PSm.yaml, device-types/Allied Telesis/GS980MX-52.yaml, device-types/Allied Telesis/GS980MX-52PSm.yaml
Added new Allied Telesis switch models (GS980MX series)
=> Added Allied Telesis GS980MX series

device-types/Arista/DCS-7280SR-48YC6.yaml
See: https://www.arista.com/assets/data/pdf/Datasheets/7280R-DataSheet.pdf
=> Add Arista DCS-7280SR-48YC6

device-types/Juniper/SRX4200.yaml
Adding SRX4200 which basically is a copy of SRX4100.
=> Adding Juniper SRX4200

device-types/Juniper/MX240.yaml, device-types/Juniper/MX960.yaml
Added Juniper MX240 and MX960 (MX480 already existed).
=> Add Juniper MX240, MX960

device-types/Rohde und Schwarz/SITLine-ETH-40G.yaml, device-types/Rohde und Schwarz/SITLine-ETH-4G.yaml, device-types/Rohde und Schwarz/TrustedVPN-L.yaml, device-types/Rohde und Schwarz/TrustedVPN-XL.yaml
* SITLineETH 4G and 40G
* TrustedVPN-L and XL
=> Add devices from Rohde&Schwarz Cybersecurity

device-types/LANCOM/ISG-1000.yaml, device-types/LANCOM/ISG-4000.yaml, device-types/LANCOM/ISG-8000.yaml
- ISG-1000
- ISG-4000
- ISG-8000
=> Add LANCOM ISG Series

device-types/Cisco/N3K-C3064PQ-10GX.yaml
=> Nexus C3064PQ-10GE

device-types/LANCOM/GS-3126X.yaml, device-types/LANCOM/GS-3126XP.yaml, device-types/LANCOM/GS-3152X.yaml, device-types/LANCOM/GS-3152XP.yaml, device-types/LANCOM/GS-3152XSP.yaml
- GS-3126X
- GS-3126XP
- GS-3152X
- GS-3152XP
- GS-3152XSP
=> Add LANCOM GS-31xx Series

device-types/LANCOM/GS-1108.yaml, device-types/LANCOM/GS-1108P.yaml
=> Add LANCOM GS-1108 Series

device-types/CyberPower/cps1220rms.yaml, device-types/Synology/RS3617RPxs.yaml
=> Synology rs3617rpxs

device-types/LANCOM/LN-1700.yaml, device-types/LANCOM/LN-1700B.yaml, device-types/LANCOM/LN-1700UE.yaml, device-types/LANCOM/LN-1702.yaml, device-types/LANCOM/LN-1702B.yaml
- LN-1700
- LN-1700B
- LN-1700UE
- LN-1702
- LN-1702B
=> Add LANCOM LN-17xx Series

device-types/LANCOM/WLC-1000.yaml, device-types/LANCOM/WLC-30.yaml, device-types/LANCOM/WLC-4006-plus.yaml, device-types/LANCOM/WLC-4025-plus.yaml, device-types/LANCOM/WLC-4025.yaml, device-types/LANCOM/WLC-4100.yaml
- WLC-30
- WLC-1000
- WLC-4006+
- WLC-4025
- WLC-4025+
- WLC-4100
=> Add LANCOM WLC Series

device-types/LANCOM/GS-3510XP.yaml, device-types/LANCOM/GS-3528X.yaml, device-types/LANCOM/GS-3528XP.yaml
- GS-3510XP
- GS-3528X
- GS-3528XP
=> Add LANCOM GS-35xx Series

device-types/TrippLite/SMART1500RMXL2UA.yaml
add smart1500rmxl2ua, 1350 watt model
=> add new smart ups model

device-types/MikroTik/RBLHGR&R11e-LTE-US.yaml, device-types/MikroTik/RBLHGR&R11e-LTE6.yaml, device-types/MikroTik/RBLtAP-2HnD.yaml, device-types/MikroTik/RBSXTR&R11e-LTE6.yaml
add some mikrotik lte products
=> add mikrotik sxt, lhg, and ltap models

device-types/Dell/Networking_N3248TE-ON.yaml
This is based off the spec sheet at
https://www.delltechnologies.com/asset/en-us/products/networking/technical-support/dell-networking-n3200-powerswitch-specsheet.pdf
=> Dell N3248TE-ON network switch

device-types/Brocade/g610.yaml, device-types/Brocade/g620.yaml, device-types/Brocade/g630.yaml
This is same as #503 but clean, since I somehow managed to mess the PR up completely.
=> [Brocade] G600 Series fibrechannel switches

device-types/Dell/Unity_XT_880F.yaml, device-types/Dell/Unity_XT_DAE.yaml
Adding following devices:
- 880F which is a storage controller
- DAE Expansion which is a expansion enclosure for all Unity devices.
=> [Dell] Adding Unity XT 880F

device-types/Cisco/ASR1001.yaml
Added the Cisco ASR1001 device type
=> Added Cisco ASR1001

device-types/Mellanox/SB7800.yml
new device type Mellanox SB7800
=> Adding Mellanox SB7800

device-types/Cisco/APIC-L3.yaml, device-types/Cisco/APIC-M3.yaml, device-types/Cisco/N2K-C2248TP-1GE.yaml, device-types/Cisco/N2K-C2248TP-E-1GE.yaml, device-types/Cisco/N2K-C2348TQ-10G-E.yaml, device-types/Cisco/N2K-C2348TQ-10GE.yaml, device-types/Cisco/N2K-C2348UPQ-10GE.yaml, device-types/Cisco/N5K-C5696Q.yaml, device-types/Cisco/N9K-C9332C.yaml, device-types/Cisco/WS-C3850-12S-E.yaml
- APIC-M3 and APIC-L3
- N2K-C2248TP-1GE and N2K-C2248TP-E-1GE
- N2K-C2348TQ-10GE, N2K-C2348TQ-10G-E and N2K-C2348UPQ-10GE
- N5K-C5696Q
- N9K-C9332C
- WS-C3850-12S-E
=> Add new Cisco devices

device-types/Ciena/3926.yaml, device-types/Ciena/3930.yaml
Add Ciena 3926 and 3930 switches
=> Create Ciena 39xx

device-types/Ubiquiti/UDM-Pro.yaml
I guess it is a typo ;-)
The Device is called UDM-PRO.
=> Fixed Typo in the Name

device-types/Extreme Networks/715W_AC_PSU_FB.yaml, device-types/Extreme Networks/X460-G2-24t-10GE4.yaml, device-types/Extreme Networks/X460-G2-48p-10GE4.yaml, device-types/Extreme Networks/X460-G2_VIM-2x.yaml
This PR creates some Extreme Networks X460-G2 series components, including:
* X460-G2-24t-10GE4
* X460-G2-48p-10GE4
* X460-G2_VIM-2x
* 715W_AC_PSU_FB
As this is my first contribution to this project, I'm trying to get some experience (not a regular Github contributer yet), therefore starting with two switches, an expansion module and a PSU component, eventually trying to add some other (not all!) components from this series later.
=> Create Extreme Networks X460-G2 series components

device-types/QNAP/ts-1283xu-rp.yml
https://www.qnap.com/en/product/ts-1283xu-rp
=> Add QNAP TS-1283XU-RP

device-types/Aruba/6200F-24G-JL724A.yaml, device-types/Aruba/6200F-24G-PoE-370W-JL725A.yaml, device-types/Aruba/6200F-48G-JL726A.yaml, device-types/Aruba/6200F-48G-PoE-370W-JL727A.yaml, device-types/Aruba/6200F-48G-PoE-740W-JL728A.yaml
* 6200F-24G-JL724A.yaml
* 6200F-24G-PoE-370W-JL725A.yaml
* 6200F-48G-JL726A.yaml
* 6200F-48G-PoE-740W-JL728A.yaml
=> Aruba: Add missing Aruba 6200F Devices

device-types/Netgear/GS105.yaml, device-types/Netgear/GS105E.yaml, device-types/Netgear/GS108.yaml, device-types/Netgear/GS108E.yaml
- GS105.yaml
- GS105E.yaml
- GS108.yaml
- GS108E.yaml
=> Netgear: Add missing Netgear GS10x Devices

device-types/Aruba/6100-12G-JL679A.yaml, device-types/Aruba/6100-24G-JL678A.yaml, device-types/Aruba/6100-24G-PoE-370W-JL677A.yaml, device-types/Aruba/6100-48G-JL676A.yaml, device-types/Aruba/6100-48G-PoE-370W-JL675A.yaml
6100-12G-JL679A
6100-24G-JL678A
6100-24G-PoE-370W-JL677A
6100-48G-JL676A
6100-48G-PoE-370W-JL675A
=> Add Aruba CX 6100 Devices

device-types/Aruba/6000-12G-R8N89A.yaml, device-types/Aruba/6000-24G-PoE-370W-R8N87A.yaml, device-types/Aruba/6000-24G-R8N88A.yaml, device-types/Aruba/6000-48G-PoE-370W-R8N85A.yaml, device-types/Aruba/6000-48G-R8N86A.yaml
* 6000-12G-R8N89A
* 6000-24G-PoE-370W-R8N87A
* 6000-24G-R8N88A
* 6000-48G-PoE-370W-R8N85A
* 6000-48G-R8N86A
Signed-off-by: Alexis La Goutte <alexis.lagoutte@gmail.com>
=> Add Aruba CX 6000 Devices

device-types/Fortinet/FG-60F.yaml
Added the FortiGate 60F device type
=> Add FortiGate 60F

device-types/F5/BIG-IP_i2600.yaml, device-types/F5/BIG-IP_i2800.yaml
=> Add F5 i2000 Series

device-types/Aruba/IAP-205.yaml, device-types/Aruba/IAP-304.yaml, device-types/Aruba/IAP-305.yaml, device-types/Aruba/IAP-315.yaml
* IAP-205
* IAP-304
* IAP-305
* IAP-315
=> Add Aruba IAP Devices

device-types/Netgear/GSM7252PS.yaml
Verified against datasheet and local hardware.
=> Adding Netgear GS752TP

device-types/Cisco/WS-C2960L-16PS-JP.yaml, device-types/Cisco/WS-C2960L-16PS-LL.yaml, device-types/Cisco/WS-C2960L-24TS-LL.yaml
* WS-C2960L-16PS-JP
* WS-C2960L-16PS-LL
* WS-C2960L-24TS-LL
=> Add Cisco WS-C2960L Devices

device-types/Cisco/C1000-48T-4G-L.yaml, device-types/Cisco/C1000-8T-2G-L.yaml
* C1000-48T-4G-L
* C1000-8T-2G-L
=> Add Cisco C1000 Devices

device-types/Cisco/WS-C3560CG-8TC-S.yaml
=> Add Cisco WS-C3560CG-8TC-S Device

device-types/Arista/DCS-7060DX4-32.yaml
=> Create Arista DCS-7060DX4-32

device-types/Arista/DCS-7060PX4-32.yaml
=> Create Arista DCS-7060PX4-32

device-types/Dell/networking-S4148T-on_Profile-3.yaml, device-types/Dell/networking-Z9100-on.yaml, device-types/Dell/networking-s3048-on.yaml, device-types/Dell/networking-s4148f-on.yaml
add dell s3048
add dell s4148t profile 3 (these switches have multiple profiles which change the available ports)
fix z9100 naming and fix interface type eth 1/1/33-34 to sfp+ 
fix s4148f naming
=> Add/Update Dell Switches

module-types/Cisco/ISR4431-X-4x1GE.yaml, module-types/Cisco/WS-X4648-RJ45V+E.yaml, module-types/Cisco/WS-X4748-RJ45V+E.yaml, module-types/Cisco/WS-X4748-UPOE+E.yaml
Adding WS-X4648-RJ45V+E
Adding WS-X4748-RJ45V+E
Adding WS-X4748-UPOE+E
Adding ISR4431-X-4x1GE
=> Adding various Cisco Cat4k & an ISR module

device-types/Ubiquiti/UAP-IW-HD.yaml
https://store.ui.com/products/unifi-in-wall-hd
=> Added UAP InWall Access Point

module-types/Cisco/N77-F348XP-23.yaml
=> Added Cisco nexus N77-F348XP-23

device-types/Cisco/SG350-28-K9.yaml
Definition of Cisco SG350-28 switch
=> Add new switch Cisco SG350-28

device-types/Cisco/WS-C2950G-48-EI.yaml
Add Cisco WS-C2950G-48-EI Device
=> Add Cisco WS-C2950G-48-EI Device

device-types/CyberPower/OR1500LCDRTXL2U.yaml
=> add new model

device-types/Cisco/CBS350-8P-E-2G.yaml, device-types/Cisco/SG300-10PP-K9.yaml, device-types/Cisco/SG350-10MP-K9.yaml, device-types/Cisco/SG350-28SFP-K9.yaml, device-types/Cisco/SG500-28-K9.yaml, device-types/Cisco/SG500X-24-K9.yaml, device-types/Cisco/SG500X-48-K9.yaml, device-types/Cisco/SG550X-24-K9.yaml, device-types/Cisco/SG550XG-24F-K9.yaml
* CBS350-8P-E-2G
* SG300-10PP-K9
* SG350-10MP-K9
* SG350-28SFP-K9
* SG500-28-K9
* SG500X-24-K9
* SG500X-48-K9
* SG550X-24-K9
* SG550XG-24F-K9
=> Add Cisco devices

device-types/Aruba/8360-12C.yaml, device-types/Aruba/8360-16Y2C.yaml, device-types/Aruba/8360-24XF2C.yaml, device-types/Aruba/8360-32Y4C.yaml, device-types/Aruba/8360-48XT4C.yaml, device-types/Aruba/8360-48Y6C.yaml
* 8360-12C (JL708A/JL709A)
* 8360-16Y2C (JL702A/JL703A)
* 8360-24XF2C (JL710A/JL711A)
* 8360-32Y4C (JL700A/JL701A)
* 8360-48XT4C (JL706A/JL707A)
* 8360-48Y2C (JL704C/JL705C)
=> Add Aruba 8630 Series

device-types/MikroTik/CRS354-48P-4S+2Q+RM.yaml
=> add CRS354-48P-4S+2Q+RM

device-types/Extreme Networks/X440-G2-24p-10GE4.yaml, device-types/Extreme Networks/X440-G2-24t-10GE4.yaml, device-types/Extreme Networks/X440-G2-24x-10GE4.yaml
Manufacturer: Extreme Networks 
Model:cX440-G2-24t-10GE4
=> add Extreme Networks X440-G2-24[txp]-10GE4

device-types/Check Point/1500_3600_3800-RM-DUAL.yaml, device-types/Check Point/4-10F-C.yaml, device-types/Check Point/4-1F-C.yaml, device-types/Check Point/8-1C-C.yaml, device-types/Check Point/SG3600.yaml, device-types/Check Point/SG6400.yaml
Manufacturer: Check Point
Model: SG3600
Manufacturer: Check Point
Model: SG6400
Manufacturer: Check Point
Model: 4-1F-C
Manufacturer: Check Point
Model: 4-10F-C
Manufacturer: Check Point
Model: 8-1C-C
Manufacturer: Check Point
Model: 1500/3600/3800-RM-DUAL
=> Add CheckPoint SG3600 and SG6400

device-types/Alcatel-Lucent/OS6900-X20.yaml, device-types/Alcatel-Lucent/OS6900-X40.yaml, module-types/Alcatel-Lucent/OS-XNI-U12.yaml
Adding Alcatel-Lucent OS6900 module bays and module OS-XNI-U12
=> Add Alcatel-Lucent OS6900 module bays and module

device-types/Aruba/10000-48Y6C.yaml
R8P13A for Front to Back, R8P14A for Back to Front
=> Add ArubaCX 10000 PENSANDO (48Y6C)

device-types/Juniper/NFX250.yaml, device-types/Juniper/nfx250.yaml
The NFX serves as a 'network virtual function' platform.
It's basically a VM host plus autoprovisioning and a lot of virtual networking options to allow chaining multiple network VMs behind each other.
=> device type: Juniper NFX250

device-types/Cisco/ISR4461.yaml
=> Add Cisco ISR4461-X

device-types/Cisco/WS-C2960X-24TS-LL.yaml
=> Add: Cisco WS-C2960X-24TS-LL

device-types/Dell/PowerEdge_R640.yaml, device-types/Lenovo/SR630.yaml, device-types/Lenovo/SR650.yaml, device-types/Lenovo/ThinkSystem_AUKJ.yaml, device-types/Lenovo/ThinkSystem_AUKK.yaml
Manufacturer: Lenovo
Models: 7ZT7A00546 & 7ZT7A00547
=> Add Lenovo 10Gb SFP+ LOMs

device-types/Cisco/C9300-24T-E.yaml, device-types/Cisco/C9300-48P-E.yaml
=> Add: Cisco C9300-24T-E and C9300-48P-E

device-types/Allied Telesis/x908Gen2.yaml
Fix device height in template.
=> Fix device height (SwitchBlade x908 Gen2)

device-types/Aruba/IAP-515.yaml
=> Add Aruba IAP-515

device-types/Ubiquiti/AF-60-HD.yml, device-types/Ubiquiti/AF-60-LR.yml, device-types/Ubiquiti/AF-60.yml
Add Ubiquiti AirFiber 60 family.
=> Add ubnt af 60

device-types/Cisco/C1000-16FP-2G-L.yaml
=> Add: Cisco C1000-16FP-2G-L

device-types/Aruba/ec-l-nm.yaml, device-types/Aruba/ec-m-b.yaml, device-types/Aruba/ec-s-p.yaml, device-types/Aruba/ec-s.yaml, device-types/Aruba/ec-us.yaml, device-types/Aruba/ec-v.yaml, device-types/Aruba/ec-xs-gen1.yaml, device-types/Aruba/ec-xs-gen2.yaml
Added Aruba SDWAN appliances as new device-type
e.g. ec-m
ec == EdgeConnect
m ==  model medium (performance class)
Details are are available on the Aruba website
https://www.arubanetworks.com/techdocs/sdwan/media/hardware/reference/EdgeConnect-Hardware-Reference-latest.pdf
=> Aruba-EdgeConnect

device-types/Dell/PowerEdge_R320.yaml
New server
https://dl.dell.com/topicspdf/poweredge-r320_owners-manual_en-us.pdf
=> [Add] R320

device-types/FS/S3900-24T4S.yaml
New switch
https://img-en.fs.com/file/datasheet/s3900-series-switches-datasheet.pdf
=> [Add] S3900-24T4S

device-types/Brocade/icx6650-64.yaml
New switch
https://www.dataswitchworks.com/datasheets/switches/icx-6650-ds.pdf
=> [Add] ICX 6650-64

device-types/Parks/Fiberlink_30028.yaml, device-types/V-Solution/V-Solution_V1600D2.yaml
In lack for a better option, PON interfaces was marked as GE but it isn't,  but I hope to see https://github.com/netbox-community/netbox/issues/8595 implemented in near future !
=> add Parks Fiberlink 30028 GPON OLT and V-Solution V1600D2 EPON OLT

device-types/Cisco/N9K-C93108TC-FX3P.yaml, device-types/Cisco/N9K-C9316D-GX.yaml, device-types/Cisco/N9K-C93180YC-FX.yaml, device-types/Cisco/N9K-C93180YC-FX3.yaml, device-types/Cisco/N9K-C93216TC-FX2.yaml, device-types/Cisco/N9K-C9348GC-FXP.yaml, device-types/Cisco/N9K-C93600CD-GX.yaml, device-types/Cisco/N9K-C9364C-GX.yaml
added all GX Cisco N9K models some FX2/FX3 Cisco N9K models
fixed some EX/FX/FX2 Cisco N9K models
=> added and fixed some Cisco Nexus 9300 models

device-types/Cisco/C9200-24P.yaml, device-types/Cisco/C9200-24T.yaml, device-types/Cisco/C9200-48P.yaml, device-types/Cisco/C9200-48T.yaml
* Add module-bays to Catalyst 9200-24P
* Add module-bays to Catalyst 9200-24T
* Add module-bays to Catalyst 9200-48P
* Add module-bays to Catalyst 9200-48T
This can be verified here : https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-9200-series-switches/nb-06-cat9200-ser-data-sheet-cte-en.html
=> Add cisco module bays to 9200 series

device-types/Arista/DCS-7050T-64.yaml
This is basically the DCS-7050S-64 but with 10GBaseT instead of SFP+.
=> Provide definition for Arista DCS-7050T-64

device-types/Fortinet/FG-1800F.yaml
Initial add of Fortinet Fortigate 1800F
=> Add Fortinet FortiGate FG1800F

device-types/Ciena/3928.yaml
Adding the AC powered version of the Ciena 3928 platform
=> Adding Ciena 3928

device-types/Juniper/EX2200-48T-4G.yaml, device-types/Juniper/EX2200-C-12P.yaml, device-types/Juniper/EX2200-C-12T.yaml, device-types/Juniper/EX2300-C-12P.yaml, device-types/Juniper/EX2300-C-12T.yaml, device-types/Juniper/EX3300-24P.yaml, device-types/Juniper/EX3300-24T.yaml, device-types/Juniper/EX3300-48P.yaml, device-types/Juniper/EX3400-24P.yaml, device-types/Juniper/EX3400-24T.yaml, device-types/Juniper/EX3400-48P.yaml, device-types/Juniper/EX4300-48P.yaml, device-types/Juniper/EX4300-48T.yaml, device-types/Juniper/QFX5100-48S-3AFO.yaml, device-types/Juniper/QFX5100-48S-6Q.yaml, device-types/Juniper/QFX5100-96S-8Q.yaml, device-types/Juniper/SRX-1500.yaml, module-types/Juniper/EX-UM-4x4SFP.yaml
I'm adding some models that I'd need (EX3300 and QFX5100 variants). Added u_height values, console ports, and interfaces to some existing models. Removed some incorrect interfaces (e.g. the EX3400 does not have four 40G ports.), and explicit "mgmt_only: false" on certain ports.
=> add or update several Juniper models

device-types/Edgecore/5812-54X-O-AC-B.yaml
=> Add new Edcore manufacturer and 5812-54X-O-AC-B device

device-types/Cisco/Meraki-MS125-24P.yaml, device-types/Cisco/Meraki-MS125-48FP.yaml, device-types/Cisco/Meraki-MS125-48LP.yaml, device-types/Cisco/N9K-C9336PQ.yaml
This PR adds device type definitions for
- Cisco Nexus 9336PQ ACI Spine Switch
- Cisco Meraki MS125-24P
- Cisco Meraki MS125-48FP
- Cisco Meraki MS125-48LP
=> Add some Cisco gear

module-types/Intel/XL710-QDA2.yaml
Create the Intel manufacturer and Intel XL710-QDA2 Network module
=> XL710-QDA2 module

device-types/Ubiquiti/EP-R6.yaml, device-types/Ubiquiti/EP-R8.yaml
Added Ubnt EdgePoint Router 6-port and 8-port
=> Add ubnt edgepoint r6

device-types/Ubiquiti/ER-12.yaml, device-types/Ubiquiti/ER-12P.yaml
Added Ubiquiti EdgeRouter 12 and 12P
=> Add ubnt edgerouter 12

device-types/Supermicro/SYS-2028U-E1CNR4T.yml
SYS-2028U-E1CNR4T+ supermicro server device-type
=> New device SYS-2028U-E1CNR4T+

device-types/Corning/EDGE-01U-SP.yaml, device-types/Corning/EDGE-01U.yaml, device-types/Corning/EDGE-02U.yaml, device-types/Corning/EDGE-04U.yaml, module-types/Corning/ECM-UM-12-04-89G.yaml, module-types/Corning/ECM-UM-12-05-93Q.yaml, module-types/Corning/ECM-UM-12-05-93T.yaml, module-types/Corning/ECM-UM-12-05-93V.yaml
Add Initial set of Corning EDGE patch panels and modules.
=> Add Corning EDGE Patch Panels and Modules

device-types/Synology/DS1522+.yaml
---
Signed-off-by: KOSHIKAWA Kenichi <reishoku.misc ~~@~~ pm.me>
=> Add Synology DS1522+

device-types/Dell/Networking_N1124P-ON.yaml
=> Add Dell N1124P-ON

device-types/ADVA/XG120-PRO-SH.yaml, device-types/ADVA/XG418-100G-CFP2.yaml, device-types/ADVA/XG418-100G.yaml, device-types/ADVA/XG480-100G-CFP2.yaml, device-types/ADVA/XG480-100G.yaml, device-types/ADVA/XG480-25G-100G.yaml
Add device types for
* ADVA FSP 150-XG120-PRO-SH
* ADVA FSP 150-XG418-100G-CFP2
* ADVA FSP 150-XG418-100G
* ADVA FSP 150-XG480-100G-CFP2
* ADVA FSP 150-XG480-100G
* ADVA FSP 150-XG480-25G-100G
=> Add ADVA XG120, XG418 and XG480

device-types/SonicWall/NSa5700.yaml
Add SonicWall NSa5700 as new product
=> Add SonicWall NSa5700

device-types/Ubiquiti/UF-OLT.yaml
=> Add ubnt uf olt

module-types/Juniper/SRX600-PWR-645AC- POE.yaml
=> SRX550 AC Power supply

device-types/Cisco/FPR4110-NGFW-K9.yaml, device-types/Cisco/FPR4112-NGFW-K9.yaml, device-types/Cisco/FPR4115-NGFW-K9.yaml, device-types/Cisco/FPR4120-NGFW-K9.yaml, device-types/Cisco/FPR4125-NGFW-K9.yaml, device-types/Cisco/FPR4140-NGFW-K9.yaml, device-types/Cisco/FPR4145-NGFW-K9.yaml, device-types/Cisco/FPR4150-NGFW-K9.yaml, module-types/Cisco/FPR4K-NM-2X100G.yaml, module-types/Cisco/FPR4K-NM-4X100G.yaml, module-types/Cisco/FPR4K-NM-4X40G.yaml, module-types/Cisco/FPR4K-NM-8X10G.yaml
- Add position to module bays
- Add module-types
=> Cisco Firepower 4100

device-types/Deciso/DEC740.yaml, device-types/Deciso/DEC750.yaml
Add Deciso models:
- DEC740
- DEC750
=> Add Deciso Security Appliances.

device-types/Ubiquiti/USW-48-PoE.yaml
Added POE Information for Ubiquiti USW-48-POE.
=> Added POE Information

device-types/Dell/DMPU2016-G01.yml
Added the Dell (Avocent rebranded) DMPU2016-G01 KVM Switch
=> Dell KVM Switch - Dell DMPU2016-G01

device-types/Dell/DKMMLED185-207.yml
Added the DKMMLED185-207 which pairs with the DMPU2016-G01
=> Dell KVM Monitor - DKMMLED185-207 

device-types/Cisco/SG350XG-24T.yaml
=> Cisco SMB Switch - SG350XG-24T

device-types/Dell/PowerVault_ME4024.yml
Added Dell PowerVault Storage ME4024
=> Dell Storage - PowerVault Storage ME4024

device-types/Dell/DR4100.yml
=> Dell Disaster Recovery Server - DR4100

device-types/Dell/Storage_NX3240.yml
Added the Dell NX3240 with its default 10G configuration
=> Dell EMC Storage - NX3240

device-types/QNAP/TS-212.yml, device-types/QNAP/TS-412.yml, device-types/QNAP/TS-453U-RP.yml, device-types/QNAP/TS-453mini.yml, device-types/QNAP/TS-469L.yml, device-types/QNAP/TS-469U-RP.yml, device-types/QNAP/TS-873.yml
Add QNAP models:
- TS-212
- TS-412
- TS-453mini
- TS-469L
- TS-469U-RP
- TS-453U-RP
- TS-873
=> Add QNAP models

device-types/Eaton/EMAT09-10.yml
Added the Eaton EMAT09-10 Smart PDU
=> Eaton Smart PDU - EMAT09-10

device-types/Cisco/C1000-16FP-2G-L.yaml, device-types/Cisco/C1000-16P-2G-L.yaml, device-types/Cisco/C1000-16P-E-2G-L.yaml, device-types/Cisco/C1000-16T-2G-L.yaml, device-types/Cisco/C1000-16T-E-2G-L.yaml, device-types/Cisco/C1000-24FP-4G-L.yaml, device-types/Cisco/C1000-24FP-4X-L.yaml, device-types/Cisco/C1000-24P-4G-L.yaml, device-types/Cisco/C1000-24P-4X-L.yaml, device-types/Cisco/C1000-24T-4G-L.yaml, device-types/Cisco/C1000-24T-4X-L.yaml, device-types/Cisco/C1000-48FP-4G-L.yaml, device-types/Cisco/C1000-48FP-4X-L.yaml, device-types/Cisco/C1000-48P-4G-L.yaml, device-types/Cisco/C1000-48P-4X-L.yaml, device-types/Cisco/C1000-48T-4G-L.yaml, device-types/Cisco/C1000-48T-4X-L.yaml, device-types/Cisco/C1000-8FP-2G-L.yaml, device-types/Cisco/C1000-8FP-E-2G-L.yaml, device-types/Cisco/C1000-8P-2G-L.yaml, device-types/Cisco/C1000-8P-E-2G-L.yaml, device-types/Cisco/C1000-8T-2G-L.yaml, device-types/Cisco/C1000-8T-E-2G-L.yaml, device-types/Cisco/C1000FE-24P-4G-L.yaml, device-types/Cisco/C1000FE-24T-4G-L.yaml, device-types/Cisco/C1000FE-48P-4G-L.yaml, device-types/Cisco/C1000FE-48T-4G-L.yaml, schema/components.json
Added all missing Cisco C1000 and C1000FE switches. Synchronized definition of Cisco C1000 switches.
=> Improve existing Cisco C1000 switches and add missing ones

module-types/Broadcom Corporation/NetXtreme-BCM5719-4P.yaml
=> Added module type Broadcom NetXtreme BCM5719-4P

device-types/Generic/wall-box-2-utp.yaml, device-types/Generic/wall-box-3-utp.yaml, device-types/Generic/wall-box-4-utp.yaml, device-types/Generic/wall-box-6-utp.yaml
Added Wall boxes with 2, 3, 4 and 6 UTP plugs.
They can be used for documenting physical wiring.
=> Added Wall boxes with 2, 3, 4 and 6 UTP plugs.

device-types/MikroTik/RB750Gr3.yaml
Added the PoE In function and the correct Power Input.  Also comment to the Datasheet
=> Mikrotik RB750Gr3 added more Details to existing Device-Type

device-types/MikroTik/RB960PGS.yaml
Added PoE in/out specs, powerport, datasheet link.
=> Updating Mikrotik RB960PGS Device Type with more Details

device-types/MikroTik/RB5009UPr+S+IN.yaml
=> Added RB5009UPr+S+IN

device-types/MikroTik/RB5009UG+S+IN.yaml
Added Device Type with Details
=> Added RB5009UG+S+IN

device-types/TP-Link/T2600G-28TS.yaml
Created the Device Type for the TP-Link T2600G-28TS Switch
=> Created TP-Link T2600G-28TS Switch Device-Type

device-types/APC/SMT3000RMI2UC.yaml, device-types/TP-Link/T2600G-28TS.yaml
Added Device-Type for APC UPS SMT3000RMI2UC
=> Create APC UPS SMT3000RMI2UC

device-types/Ruckus/icx-7150-48p-4x10g.yaml
Added Device Type for Ruckus icx-7150-48p-4x10g Switch
=> Create Ruckus icx-7150-48p-4x10g.yaml Switch

device-types/MikroTik/RB2011UiAS-RM.yaml
Added more Details and the PoE Details to the Device-Type
=> Update RB2011UiAS-RM.yaml with more Details and PoE

device-types/MikroTik/RB2011iL-RM.yaml
Updating with PoE and some more Details.
=> Update RB2011iL-RM.yaml with PoE and other Details

device-types/Check Point/SG23800.yaml, module-types/Check Point/2-10FSR-BP-B.yaml, module-types/Check Point/4-10F-C.yaml, module-types/Check Point/4-1C-BP-B.yaml, module-types/Check Point/4-1F-C.yaml, module-types/Check Point/8-1C-C.yaml
Commits should be self-explanatory.
Modules are incorrectly categorized as devices so I moved and changed the templates.
=> Check Point: Add SG23800 and add/move modules

.gitignore, device-types/Synology/DS418.yaml
Since @basictheprogramm hasnt gotten back to us about fixing his PR, I went ahead and did so for him. I could not fix the newline issue without access to his repo, so instead I created a branch on my local repo
This is to fix #979
=> #979 @basictheprogramm synology ds418 fix

device-types/MikroTik/CCR1036-8G-2S+.yaml
Added the airflow direction only
=> Update CCR1036-8G-2S+.yaml with Airflow direction

device-types/MikroTik/CCR1009-7G-1C-1S+.yaml
=> Update CCR1009-7G-1C-1S+.yaml airflow direction

device-types/Cisco/Meraki-MX450.yaml
Create Meraki-MX450.yaml from the Meraki MX family (similiar to the MX250 etc.)
=> Create Cisco Meraki-MX450.yaml

device-types/MikroTik/CCR1009-7G-1C-1S+PC.yaml
added airflow, power port and poe input specs
=> Updated CCR1009-7G-1C-1S+PC.yaml

device-types/RAD/ETX-2i-10G.yaml
Create First Device from RAD ( https://rad.com/ ) https://www.rad.com/resources/etx-2i-10g-devices-data-sheet
=> Create RAD ETX-2i-10G.yaml

device-types/Cisco/ASA5505.yaml, device-types/Cisco/ASA5510.yaml, device-types/Cisco/ASA5520.yaml, device-types/Cisco/ASA5540.yaml, module-types/Cisco/ASA-SSC-AIP-5.yaml, module-types/Cisco/ASA-SSM-4GE.yaml, module-types/Cisco/ASA-SSM-AIP-10.yaml, module-types/Cisco/ASA-SSM-AIP-20.yaml, module-types/Cisco/ASA-SSM-AIP-40.yaml, module-types/Cisco/ASA-SSM-CSC-10.yaml, module-types/Cisco/ASA-SSM-CSC-20.yaml
Various tweaks to the old but gold ASA5500 line of firewalls. Added module bays where present and included applicable SSM/ SSC module types.
=> AIP/ CSC SSM updates for the ASA

device-types/Eaton/9PX5KIRTN.yaml, device-types/Eaton/9PXEBM180.yaml, device-types/Eaton/CBL2OUT32.yaml, device-types/Eaton/ESWB05.yaml, device-types/Eaton/ESWB22.yaml
=> Eaton PSU, EBM and PDUs

device-types/Dell/PowerVault_ME4024.yml
Fixes to positions for Dell ME4024 Controllers
=> Dell ME4024 Fixes

device-types/Dell/PowerEdge_1950.yaml
Added Device Type for Dell PowerEdge_1950.yaml
=> Create Dell PowerEdge_1950.yaml Device Type

module-types/Synology/E10M20-T1.yaml
=> add synology e10m20-t1.yaml

device-types/MikroTik/CRS226-24G-2S+RM.yaml
Create new Device Type for Mikrotik CRS226-24G-2S+RM
=> Create CRS226-24G-2S+RM.yaml Device Type model

device-types/Cisco/WS-C3750-48TS-S.yaml
This device has 2 stack ports so I've added them here.
=> Added stack ports

device-types/APC/SMT2200RMI2UNC.yaml
=> Add APC SMT2200RMI2UNC

device-types/Juniper/SRX110H2-VA.yaml
=> Adding srx110h2-va

README.md, schema/components.json, schema/devicetype.json, schema/moduletype.json
Added the required validation information for the addition of weight as described in #1060
=> Added weight to device and module types

device-types/FS/FMU-MC084761EM3.yaml
Created FS FMU-MC084761EM3.yaml CWDM as child device
References(End of Sale) :
https://www.fs.com/de/products/72428.html
https://community.cisco.com/kxiwq67737/attachments/kxiwq67737/5486-discussions-optical-networking/8573/1/8ch-cwdm-mux-demux-1470-1610-with-exp-mon-and-1310.pdf
=> Create FS FMU-MC084761EM3.yaml CWDM

device-types/Datacom/DM4610-OLT-4GPON+4GX+2XS.yaml, module-types/Datacom/FAN_OLT-DM4610.yaml, module-types/Datacom/PSU-120-AC_OLT-DM4610.yaml, module-types/Datacom/PSU-120-DC_OLT-DM4610.yaml
Hi,
Adding equipment from the manufacturer DATACOM.
Added only 1 equipment for validation.
Upon receiving the OK, I will add the other equipment.
=> Adding equipment from the manufacturer DATACOM.

requirements.txt
manually applying dependabot version changes
=> Dependabot version updates

device-types/A10/TH4440.yaml, device-types/A10/TH6430.yaml
=> A10 device cleanup

device-types/Adtran/MX2800.yaml, device-types/Adtran/TA-5000-23in.yaml
Fixed MX2800 part number, added product link
Fixed TA-5000 23 inch file name (new TA5000 has same name without 23 inch specification), slug and added product link
=> Adtran Device Cleanup

device-types/ADVA/FSP_150-XG120PRO-SH.yaml, device-types/ADVA/FSP_150-XG418-100G-CFP2.yaml, device-types/ADVA/FSP_150-XG418-100G.yaml, device-types/ADVA/FSP_150-XG480-100G-CFP2.yaml, device-types/ADVA/FSP_150-XG480-100G.yaml, device-types/ADVA/FSP_150-XG480-25G-100G.yaml
FSP 150-XG120Pro (SH) fixed model name/slug, file name, added allocated draw and product page
FSP 150-XG418-100G-CFP2 fixed model name/slug, file name, added allocated draw and product page
FSP 150-XG418-100G fixed model name/slug, file name, added allocated draw and product page
FSP 150-XG480-100G-CFP2 fixed model name/slug, file name, added allocated draw and product page
FSP 150-XG480-100G fixed model name/slug, file name, added allocated draw and product page
FSP 150-XG480-25G-100G fixed model name/slug, file name, added allocated draw and product page
=> ADVA Device cleanup

device-types/Inspur/NF5180M6.yaml
Create a template for Inspur NF5180M6 server platform.
=> Create a template for Inspur NF5180M6

device-types/Huawei/S5700-28X-LI-AC.yaml
Add Huawei S5700-28X-LI-AC switch
=> Add Huawei S5700-28X-LI-AC switch

device-types/APC/SMT1500.yaml, device-types/APC/SMT1500RM2U.yaml, device-types/APC/SRT3000RMXLT.yaml, device-types/APC/SRT5KRMXLT.yaml
Added missing ports, corrected outlet groupings, standardized models.
=> Update Smart-UPS models and ports

device-types/Fortinet/FG-100E.yaml, device-types/Fortinet/FG-100F.yaml, device-types/Fortinet/FG-140E-POE.yaml, device-types/Fortinet/FG-200E.yaml, device-types/Fortinet/FG-200F.yaml, device-types/Fortinet/FG-60F.yaml, device-types/Fortinet/FG-80E-POE.yaml, device-types/Fortinet/FG-80E.yaml, device-types/Fortinet/FG-81E-POE.yaml
Added missing power ports, updated incorrect power ports, added new PoE fields, updated comments to descriptions.
=> Update fortinet firewalls

module-types/Intel/I350-T2.yaml, module-types/Intel/I350-T4.yaml, module-types/Intel/X550-T2.yaml
Hi,
This is a pull request to add Intel NIC card as modules for server compute.
Regards,
=> Adding Intel NIC cards.

module-types/APC/AP9630.yaml, module-types/APC/AP9631.yaml, module-types/APC/AP9640.yaml, module-types/APC/AP9641.yaml
Updated missing ports on APC NMC modules
=> Update APC NMC module ports

device-types/Cisco/Meraki-MS225-48LP.yaml, device-types/Cisco/Meraki-MS425-32.yaml, module-types/Cisco/Meraki-MA-PWR-250WAC.yaml
Updated missing and incorrect ports for Meraki switches.
=> Update meraki ports

device-types/Cisco/RV220W.yaml, device-types/Datto/AP440.yaml, device-types/Datto/DSW100-24P-4X.yaml
Added the following devices:
- Datto AP440
- DSW100-24P-4x
- Cisco RV220W
=> Add Datto Networking & Cisco RV220W

device-types/Cisco/DPC3939B.yaml
Added Comcast Business - Cisco DPC3939B
https://www.compsource.com/pdfs/pdf_new/29606.pdf
=> Added Comcast Business - Cisco DPC3939B

device-types/QNAP/TS-453B.yml
Some customers still use this legacy model.
=> Add QNAP 453B

device-types/Datto/DSW100-8P-2G.yaml
=> Adding Datto DSW100-8P-2G

device-types/HPE/FlexFabric-5945-2-slot.yaml
=> added HPE FlexFabric-5945-2-slot

device-types/HPE/FlexNetwork-5510-24G-SFP-4SFPP-HI.yaml, device-types/HPE/FlexNetwork-5510-48G-POEP-4SFPP-HI.yaml
and updated FlexNetwork-5510-48G-POEP-4SFPP-HI with port expansion module
=> added FlexNetwork-5510-24G-SFP-4SFPP-HI

device-types/HPE/Aruba-2930M-48G-PoEP.yaml, device-types/HPE/Aruba-2930M-48G.yaml
=> added Aruba-2930M-48G: JL321A and JL322A

device-types/Synology/DS118.yaml
=> Added Synology DS118

device-types/Datto/AP440.yaml, device-types/Datto/AP840.yaml, device-types/Datto/AP840E.yaml, device-types/Datto/D200.yaml, device-types/Datto/DNA.yaml, device-types/Datto/DSW100-24P-4X.yaml, device-types/Datto/DSW100-84P-4X.yaml, device-types/Datto/DSW100-8P-2G.yaml, device-types/Datto/DSW250-8P-2X.yaml, module-types/Datto/ANT24805045-DP460.yml
Addition of Datto Networking Hardware and some fixes to them as well
=> Datto Networking Hardware

device-types/Cisco/SPA112.yaml
It has been determined for the time being that FXS/FXO fall directly under the `other` category. If we ever implement device interface types for FXS/FXO we can update this device
=> Cisco SPA112

device-types/Ubiquiti/ER-X.yaml
=> Improved comments in ubiquiti er-x

device-types/Ruckus/r350.yaml
Create Ruckus R350 WiFi Access Point after Datasheet and with Live reference. https://www.commscope.com/globalassets/digizuite/921208-ds-ruckus-r350.pdf
=> Create Ruckus R350 WiFi Access Point

device-types/Ubiquiti/USW-Enterprise-24-PoE.yaml
add ubiquity USW-Enterprise-48-PoE.yaml
=> Add Ubiquiti USW-Enterprise-24-PoE

.pre-commit-config.yaml
This PR introduces the addition of pytest as the final step. This will assist users when creating new files to ensure they match requirements
=> Pre-Commit: Add pytest

module-types/Cisco/nim-es2-8.yaml
Add 8-Port Gigabit Ethernet LAN Switch NIM for Cisco ISR
=> Add 8-Port Gigabit Ethernet LAN Switch NIM for Cisco ISR

module-types/Cisco/NIM-16A.yaml
Add 16-Port Async Serial NIM for Cisco ISR
=> Add 16-Port Async Serial NIM for Cisco ISR

requirements.txt
Fixes #1254
Fixes #1253 
Fixes #1252
=> bumping releases

module-types/HPE/HPE-JH180A.yaml, module-types/HPE/HPE-JH181A.yaml
Added two HPE modules:
- (JH180A) HPE 5930 24-port SFP+ and 2-port QSFP+ Module
- (JH181A) HPE 5930 24-port SFP+ and 2-port QSFP+ with MACsec Module
=> modules JH180A and JH181A

device-types/Eaton/5PX2200IRT.yaml
=> Add Eaton 5PX2200IRT

module-types/Palo Alto/PAN-PA-5400-DPC-A.yaml
Module types are available for this chassis. I will create pull requests for them as well.
PAN-PA-5400-DPC-A
PAN-PA-5400-MPC-A
PAN-PA-5400-NC-A-1
PAN-PA-5400-NC-A-2
=> PAN-PA-5400-DPC-A.yaml

device-types/HPE/Aruba-3810M-24G-1-slot.yaml, device-types/HPE/ProCurve-6108.yaml, device-types/HPE/ProCurve-E2510-24G.yaml, module-types/HPE/Aruba-JL085A.yaml
Add module-type HPE X371 as well (PSU)
=> Add Aruba 3810M, Procurve 6108 and E2510-24G

device-types/Extreme Networks/X450-G2-48p-10GE4.yaml
added extreme networks x450 g2 48p 10ge4.
=> added extreme networks x450 g2 48p 10ge4

.github/workflows/validation.yml, .pre-commit-config.yaml, .pre-commit-hooks-config.yaml, .pre-commit-yamlfmt-config.yaml, requirements.txt
Bump the following deps:
- pre-commit to 3.2.2
- pytest to 7.3.1
- yamllint to 1.31.0
=> Dependencies updates for May 2023

device-types/Cisco/ISR1118-8P.yaml
=> add cisco ISR1118-8P

module-types/Juniper/MIC-3D-16XGE-SFPP.yaml
Hi,
I am trying my first pull request on this repository.
Just added a Juniper module that was missing.
Kind Regards.
=> add juniper module MIC-3D-16XGE-SFPP

device-types/ADVA/FSP-150-CM.yaml, module-types/ADVA/FSP-150-CM-PSU.yaml, module-types/ADVA/NEMI.yaml, module-types/ADVA/NTU-GE.yaml
Adding the ADVA FSP150CM along with NEMI and NTU-GE modules
=> Add ADVA FSP150CM and associated modules

requirements.txt
- pre-commit to 3.3.2
- yamllint to 1.32.0
Fixes #1408 
Fixes #1409
=> Bumped dependancies

device-types/HPE/Aruba-IAP-505.yaml, device-types/HPE/Aruba-IAP-515.yaml
Add IAP-505
Add POE to IAP-515
=> Hpe Aruba AP

tests/definitions_test.py, tests/device_types.py
Updating comments and error messages for better readability and validation
=> Update test comments and error messages

schema/components.json
=> Test cases fail for interface type: other-wireless

tests/definitions_test.py
Reverts netbox-community/devicetype-library#1497
=> Revert "Adding failure condition for pickle file"

requirements.txt
Realted to PR#1516 and PR#1515
=> Bumping pyyaml anmd jsonschema.

requirements.txt
=> Bumping jsonschema

schema/components.json, schema/devicetype.json, schema/generated.json, schema/moduletype.json, schema/reusable.json
Updating schemas for autogenerated schema information
=> Schema Update

device-types/Arista/DCS-7150S-24-CL-F.yaml, device-types/Arista/DCS-7150S-24-CL-R.yaml, device-types/Arista/DCS-7150S-52-CL-F.yaml, device-types/Arista/DCS-7150S-52-CL-R.yaml, device-types/Arista/DCS-7150S-64-CL-F.yaml, device-types/Arista/DCS-7150S-64-CL-R.yaml, device-types/Arista/DCS-7150SC-24-CLD-F.yaml, device-types/Arista/DCS-7150SC-24-CLD-R.yaml, device-types/Arista/DCS-7150SC-64-CLD-F.yaml, device-types/Arista/DCS-7150SC-64-CLD-R.yaml
=> Arista 7150 Family (Update)

device-types/Brocade/300.yaml
Hello,
I have added the Switch "Brocade 300".
It only has the part number "300".
Power Port ist bulit in, no module.
Thank you very much in advance.
Marc
=> Add Brocade 300

device-types/Palo Alto/PA-5410.yaml, device-types/Palo Alto/PA-5420.yaml, device-types/Palo Alto/PA-5430.yaml, device-types/Palo Alto/PA-5440.yaml
Hello,
I have added four Palo Alto 5400 devices.
Pre-commit tests were successful.
Thank you very much in advance.
Marc
=> Add Palo Alto 5400 Series

device-types/Cisco/ESA-C390.yaml, module-types/Cisco/CCS-PWR-AC-770W.yaml
Hello,
I've added the Cisco ESA-C390 and a power supply module.
Thanks in Advance and Kind regards.
Marc
=> Add Cisco ESA-C390

device-types/Barracuda/Message-Archiver-350.yaml
Hello,
I've added the Barracuda Message Archiver 350.
Please merge into master branch.
Thanks in advance.
Kind regards,
Marc
=> Add Barracuda Message Archiver 350

device-types/Cisco/C9200L-24PXG-2Y.yaml, module-types/Cisco/PWR-C5-600WAC.yaml
Add Cisco C9200L-24PXG-2Y switch
=> Add Cisco C9200L-24PXG-2Y

.editorconfig
[EditorConfig](https://editorconfig.org/) helps maintain consistent coding styles
=> Added .editorconfig following CONTRIBUTING.md guidelines

device-types/Zyxel/GS1920-24.yaml
I added the V1 GS1920-24, currently the repo only contains the GS1920-24v2
=> Added GS1920-24

module-types/Intel/X520-DA1.yaml
I added the Intel X520-DA1 Network Card
=> Added X520-DA1 Network Card

module-types/Dell/2MCCT.yaml
Added the Dell 2MCCT Powersupply module
=> Added Dell 2MCCT Powersupply

requirements.txt
Updating `pre-commit`, `pytest` and `gitpython`
=> Updated Dependancies

.pre-commit-config.yaml, .pre-commit-hooks-config.yaml, requirements.txt
Updated `pre-commit` and `gitpython`
Updates pre-commit packages `pre-commit-hooks` and `yamllint`
=> Updating Dependancies and pre-commit packages

requirements.txt
Upgrading the following pip packages:
- pytest 7.4.2 > 7.4.3
- yamllint 1.32.0 > 1.33.0
- psutil 5.9.5 > 5.9.6
=> November 2023 Dependency Updates

device-types/Juniper/PTX10001-MR.yml
Ref.
https://www.juniper.net/documentation/us/en/hardware/ptx10001/topics/topic-map/ptx10001-36mr-cooling-system.html
=> PTX10001-MR: fix airflow direction, it is front-to-rear.

device-types/APC/AP8881.yaml, device-types/APC/AP8888.yaml
=> Added APC AP8881 and AP8888 PDUs

device-types/Fortinet/FS-648F.yaml
Layout identical with 648F-FPOE.
=> Added Fortiswitch 648F

module-types/Cisco/PWR-C5-125WAC.yaml, module-types/Cisco/PWR-C6-125WAC.yaml, module-types/Cisco/PWR-C6-1KWAC.yaml, module-types/Cisco/PWR-C6-600WAC.yaml, module-types/Cisco/WS-CAC-6000W.yaml
Some power supply modules from Cisco
=> add cisco power supply modules

README.md
Adding further documentation to the readme (with links back to docs.netbox.dev) to explain the different DCIM parts. Hopefully this will help with contributors understanding
=> README DCIM Updates

device-types/PC Engines/APU6.yaml
Add a Device Type for the PCEngines APU6 inside of its case
=> Add PCEngines APU6

device-types/Brocade/ICX-6450-24p.yaml
https://webresources.ruckuswireless.com/pdf/datasheets/ds-icx-6430-6450.pdf
=> feat: add brocade ICX-6450-24p

device-types/Cisco/ASR-9001.yaml, module-types/Cisco/A9K-750W-AC.yaml, module-types/Cisco/A9K-MPA-20X1GE.yaml, module-types/Cisco/A9K-MPA-4X10GE.yaml, module-types/Cisco/ASR-9001-FAN.yaml
Update ASR9000 with modular power supplies, fan
Add line cards:
* A9K-MPA-20X1GE
* A9K-MPA-4X10GE
Add power supply modules A9K-750W-AC
Add fan tray modules: ASR-9001-FAN
=> Update Cisco ASR9000 and add modules bays

device-types/Opengear/CM8148-10G.yaml, device-types/Opengear/CM8148.yaml
CM8148-10G – 48 ports
Form Factor 1 RU
https://opengear.com/fr/products/cm8100-console-server/
=> fix U height CM8148

device-types/Eaton/Tripp-Lite-B040-008-19.yaml, device-types/Generic/Blanking-Panel-1U.yaml, device-types/Generic/Blanking-Panel-2U.yaml, device-types/Generic/Storage-Drawer-2U.yaml, device-types/Generic/Storage-Drawer-4U.yaml, device-types/Generic/Vented-Blanking-Panel-1U.yaml, device-types/Generic/Vented-Blanking-Panel-2U.yaml
Added: 
-Generic blanking panel 1 & 2U
-Generic vented blanking panel 1 & 2U
-Generic Storage drawer 2 & 4U
-Tripp Lite B040-008-19 KVM
Any suggestions greatly appreciated!
=> Generic Items and Tripp Lite KVM

device-types/Cisco/ISR-1111-4PLTEEA.yaml
Add the 4-port version of Cisco ISR 1111 LTE Router
=> Add Cisco ISR-1111-4PLTEEA

device-types/Juniper/PTX10003-80C.yaml, device-types/Opengear/CM8148-10G.yaml, device-types/Opengear/CM8148.yaml, module-types/Juniper/JPSU-3000W-AC-AFO.yaml
https://www.juniper.net/us/en/products/routers/ptx-series/ptx10003-packet-transport-router.html
test on netbox : ✅
=> Add juniper ptx10003 80 c

.github/dependabot.yml, .pre-commit-config.yaml, requirements.txt
- Bump yamllint to v1.35.1
- Bump gitpython to v3.1.42
- Add dependabot update check for github actions
=> March 2024 Dependency Updates

tests/generate-slug-list.py
resolving RefResolver deprecation issue in the master slug generator
=> Master Slug Generator - JSON Schema Update

requirements.txt
Updating pytest and pre-commit
=> Pytest update

.github/workflows/update-generated-schema.yml, .github/workflows/validation.yml
- Bumping peter-evans/create-pull-request from v5 to v6 per #2035
- Bumping tj-actions/changed-files from v41 to v44 per #2033
=> Actions Updates

tests/device_types.py
Updating test cases to resolve PR #1719
- Correcting slugify methods to remove `(`, `)`, and `;`
=> Test Case Updates

device-types/Raspberry Pi/RPI-MODB.yaml, device-types/Raspberry Pi/RPI-MODBP.yaml, device-types/Raspberry Pi/RPI2-MODB.yaml, device-types/Raspberry Pi/RPI3-MODB.yaml, device-types/Raspberry Pi/RPI3-MODBP.yaml, device-types/Raspberry Pi/RPI4-MOD400.yaml, device-types/Raspberry Pi/RPI4-MODB.yaml, device-types/Raspberry Pi/RPI5.yaml
~~Add~~
- ~~Pi 1 (256M, 512M)~~
- ~~Pi 2 (1G)~~
- ~~Pi 4 400 (4G)~~
- ~~Pi 5 (4G, 8G)~~
Collapse all PI models into generation and remove memory sizes from the files at @danner26 request.
=> Device Type: Update Raspberry Pi

requirements.txt
Bump jsonschema, pytest and gitpython
=> Deps - May 2024 Update

.pre-commit-config.yaml, .pre-commit-hooks-config.yaml, requirements.txt
=> Bumping pre-commit and hook configs

device-types/Cisco/AIR-AP1852I-E-K9.yaml
Add device type for Cisco AIR-AP-1852I-E-K9
=> Add Cisco AIR-AP1852I-E-K9

device-types/Cisco/AIR-AP2802E-E-K9.yaml
Add device type for Cisco AIR-AP2802E-E-K9
=> Add Cisco AIR-AP2802E-E-K9

device-types/Cisco/AIR-AP1832I-E-K9.yaml
Add device type Add Cisco AIR-AP1832I-E-K9
=> Add Cisco AIR-AP1832I-E-K9

device-types/Cisco/C9136I-E.yaml
Add device type Cisco C9136I-E
=> Add Cisco C9136I-E

device-types/LANCOM/LW-600.yaml, device-types/LANCOM/LX-6402.yaml
=> Add LANCOM WiFi access points

device-types/Huawei/CE5855-48T4S2Q-EI.yaml
New Huawei model, primarily based on: https://support.huawei.com/enterprise/en/doc/EDOC1000019246/cb57cbba/ce5855-48t4s2q-ei
=> Add Huawei CE5855-48T4S2Q-EI

device-types/Raritan/PX3-5516.yml
Also added the USB Port, it likely should be on all PX3. It also has a Wireless connection option but I don't know how that would need to be modelled.
=> Create one Raritan PDU PX3-5516.yml

device-types/HPE/Aruba-8400.yaml, module-types/HPE/Aruba-JL363A.yaml, module-types/HPE/Aruba-JL368A.yaml
Adding the following:
- Aruba 8400
- Aruba JL368A (Management Module)
- Aruba JL363A (32 Port SFP+ Module)
=> Add HPE Aruba 8400 and 2 Complimentary Modules.

device-types/Synology/DS420+.yaml
- Add Synology DS420+ as a device type
=> Add Synology DS420+

device-types/MikroTik/RBD52G-5HacD2HnD-TC.yaml
Add device type RBD52G-5HacD2HnD-TC
=> Add Mikrotik hAP ac²

device-types/Extreme Networks/X440-G2-48p-10GE4.yaml
I extended one of the 24-port X440-G2 models to 48 ports for this X440-G2-48p-10GE4 model and filled in all details that seemed reasonable.
The sets of combo ports are a little confusing but that is just how that sort of thing goes I guess.
=> Add file for X440-G2-48p-10GE4

device-types/Generic/LSH-APC-24-port-fiber-patch-panel-full-depth.yaml, device-types/Generic/LSH-APC-24-port-fiber-patch-panel-half-depth.yaml, device-types/Generic/LSH-APC-48-port-fiber-patch-panel-full-depth.yaml, device-types/Generic/LSH-APC-48-port-fiber-patch-panel-half-depth.yaml
Based on the existing LC patchpanels.
=> Add generic LSH/APC patchpanels with 24 and 48 ports.

.github/workflows/update-generated-schema.yml, .github/workflows/validation.yml, device-types/Arista/DCS-7130LBR-48S6QD-R.yaml, requirements.txt
updating requirements, updating workflows and fixing device
=> October 2024 Dependency Updates

device-types/Dell/PowerEdge-T630.yaml
=> Created Dell PowerEdge T630 device type

device-types/Supermicro/SYS-5019P-MTR.yaml
Add Supermicro Superserver SYS-5019P-MTR - https://www.supermicro.com/products/system/1U/5019/SYS-5019P-MTR.cfm
=> Add Supermicro Superserver SYS-5019P-MTR

device-types/Supermicro/SYS-6018R-MT.yaml
Added Supermicro Superserver 6018R-MT - https://www.supermicro.com/products/system/1U/6018/SYS-6018R-MT.cfm
=> Add Supermicro Superserver SYS-6018R-MT

device-types/Supermicro/SSG-620P-E1CR24L.yaml
Add Supermicro Storage SuperServer SSG-620P-E1CR24L  - https://www.supermicro.com/en/products/system/Storage/2U/SSG-620P-E1CR24L
=> Add Supermicro Storage SuperServer SSG-620P-E1CR24L 

device-types/Supermicro/SYS-5019P-WTR.yaml, module-types/Supermicro/PWS-504P-1R.yaml
Added Supermicro Superserver SYS-5019P-WTR - https://www.supermicro.com/products/system/1U/5019/SYS-5019P-WTR.cfm
=> Add Supermicro Superserver SYS-5019P-WTR

device-types/F5/BIG-IP-i5600.yaml, device-types/F5/BIG-IP-i5800.yaml, module-types/F5/PWR-0306.yaml
Update weight and PS Module for F5 Big-IP i5000 series
=> Update F5 Big-IP i5000 series

device-types/Raritan/PX3-1045.yaml
=> Add device type PX3-1045

device-types/Supermicro/SYS-110P-WTR.yaml
Added Supermicro SuperServer SYS-110P-WTR
https://www.supermicro.com/en/products/system/WIO/1U/SYS-110P-WTR
=> Added Supermicro SuperServer SYS-110P-WTR

device-types/Supermicro/AS-1014S-WTRT.yaml
Added Supermicro SuperServer A+ Server 1014S-WTRT
https://www.supermicro.com/en/Aplus/system/1U/1014/AS-1014S-WTRT.cfm
=> Add Supermicro SuperServer A+ Server 1014S-WTRT

device-types/NEC/ap400.yaml
NEC IP DECT AP, AP400
Fixed commit issues
=> NEC IP DECT AP, AP400

AP7811B.yml, AP7911.yml, AP7930.yml, AP8941.yml
Added 4 more APC Power Supplies based on devices in my racks and specs on APC's website.
=> Added 4 more APC Power Supplies

device-types/AVM/FRITZBox-5530-Fiber.yaml, device-types/AVM/FRITZBox-5590-Fiber.yaml
Add AVM Fritz!Box 5530 and 5590 Fiber to the library.
=> Add AVM Fritz!Box 5530 and 5590 Fiber

device-types/Cisco/SG350-28MP-K9.yaml, device-types/Cisco/SG350-28P-K9.yaml, device-types/Cisco/SG350-52MP-K9.yaml, device-types/Cisco/SG350-52P-K9.yaml
Adding devices:
Cisco SG350-28P-K9
Cisco SG350-28PP-K9
Cisco SG350-52P-K9
Cisco SG350-52MP-K9
=> Cisco SG350- 28P-K9, 28PP-K9, 52P-K9 & 52MP-K9

device-types/Extreme Networks/X350-24t.yaml, device-types/Extreme Networks/X350-48t.yaml
add extreme-networks-X350-Series
*  X350-24t
*  X350-48t
Reference:  https://documentation.extremenetworks.com/summit_16/GUID-32B6E8A2-66A0-4C4E-98D2-695B9E14D98C.shtml
=> add extreme-networks-X350-Series

device-types/Cisco/C9120AXI-E.yaml, device-types/Cisco/C9120AXI-K.yaml
Add device type C9120AXI-K and fix datasheet & weight for C9120AXI-E
=> Add C9120AXI-K

device-types/Extreme Networks/X450-24t.yaml, device-types/Extreme Networks/X450-24x.yaml
add extreme-networks-X450-Series
* X450-24t
* X450-24x
Reference: https://documentation.extremenetworks.com/summit_16/GUID-491B5CBB-F604-471D-9D93-AA5D150A3F06.shtml
=> add extreme-networks-X450-Series

device-types/Extreme Networks/X450a-24t.yaml, device-types/Extreme Networks/X450a-24tDC.yaml, device-types/Extreme Networks/X450a-24x.yaml, device-types/Extreme Networks/X450a-24xDC.yaml, device-types/Extreme Networks/X450a-48t.yaml, device-types/Extreme Networks/X450a-48tDC.yaml
add extreme-networks-X450a-Series
* X450a-24t
* X450a-24x
* X450a-48t
* X450a-24tDC
* X450a-24xDC
* X450a-48tDC
Reference: https://documentation.extremenetworks.com/summit_16/GUID-363259D1-C368-4F9D-A28A-A321C9297085.shtml
=> add extreme-networks-X450a-Series

device-types/Extreme Networks/X450e-24p.yaml, device-types/Extreme Networks/X450e-24t.yaml, device-types/Extreme Networks/X450e-48p.yaml, device-types/Extreme Networks/X450e-48t.yaml
add extreme-networks-X450e-Series
* X450e-24p
* X450e-48p
* X450e-24t
* X450e-48t
Reference: https://documentation.extremenetworks.com/summit_16/GUID-8DB7D6AC-C007-4FD6-A8E0-993FCB2C2734.shtml
=> add extreme-networks-X450e-Series

device-types/Deciso/DEC2700.yaml, device-types/Deciso/DEC2750.yaml, device-types/QNAP/TS-879-pro.yml
Added  the dec2700 firewall appliances from deciso.
=> Add deciso dec2700. Pre commit checks passed.

device-types/Extreme Networks/X430-24p.yaml, device-types/Extreme Networks/X430-24t.yaml, device-types/Extreme Networks/X430-48t.yaml, device-types/Extreme Networks/X430-8p.yaml
add extreme-networks-X430-Series
* X430-8p
* X430-24p
* X430-24t
* X430-48t
Reference: https://documentation.extremenetworks.com/summit_16/GUID-F5B79310-DFD9-4B51-B291-36EDE8015A3C.shtml
=> add extreme-networks-X430-Series

device-types/Extreme Networks/X770-32q.yaml
add extreme-networks-X770-Series
* X770-32q
Reference: https://documentation.extremenetworks.com/summit_16/GUID-163CA6B4-9851-4C25-96AA-382E5785C8AF.shtml
=> add extreme-networks-X770-Series

device-types/Extreme Networks/X670-G2-48x-4q.yaml, device-types/Extreme Networks/X670-G2-72x.yaml
add extreme-networks-X670-G2-Series
* X670-G2-48x-4q
* X670-G2-72x
Reference: https://documentation.extremenetworks.com/summit_16/GUID-109416E6-1557-4395-A11D-3A95543C6785.shtml
=> add extreme-networks-X670-G2-Series

device-types/Extreme Networks/X670-48x.yaml, device-types/Extreme Networks/X670V-48t.yaml, device-types/Extreme Networks/X670V-48x.yaml
add extreme-networks-X670-Series
* X670-48t
* X670-48x
* X670-24x
Reference: https://documentation.extremenetworks.com/summit_16/GUID-5AD92882-265F-459A-B184-FD4F9079BBC2.shtml
=> add extreme-networks-X670-Series

device-types/Max Hauri/bachmann-107686.yaml
=> Add Max Hauri Bachmann 107686

device-types/Supermicro/AS-1114S-WN10RT.yml
Update AS-1114S-WN10RT.yml with datasheet, 10G RJ NICs, and dedicated BMC port.
=> added part number + comments

device-types/Supermicro/SSG-620P-E1CR24L.yaml
Spotted an issue when importing to NetBox and decided to fix it.
=> SSG-620P: fix non-ascii symbol and add some descriptions while at it.

device-types/Supermicro/AS-3015MR-H8TNR.yaml, module-types/Supermicro/AOC-C25G-m1S.yaml, module-types/Supermicro/AOC-MCX4121A-ACAT.yaml, module-types/Supermicro/AOC-S25GC-i2S.yaml, module-types/Supermicro/PWS-2K20A-1R.yml
Adding MicroCloud chassi and powersupply. 
Also adding network cards (not tied to only this chassi).
=> Add Supermicro AS-3015MR-H8TNR

device-types/Synology/RS3621xs+.yaml, module-types/Synology/E25G30-F2.yaml, module-types/Synology/PSU 500W-RP Module_2.yml, module-types/Synology/PSU 550W-RP Module_1.yml
Update RS3621xs+ and add NIC E25G30-F2, as well as 2 PSU modules.
=> Synology RS3621xs+

device-types/Meinberg/lantime-m200.yaml
=> Meinberg lantime m200

module-types/Meinberg/IMS-GXL.yml, module-types/Schweitzer Engineering Laboratories/SEL-2245-221-Low-Voltage-(LEA)-Monitoring-Module.yml, module-types/Schweitzer Engineering Laboratories/SEL-2245-3-DC-Analog-Output-Module.yml, module-types/Schweitzer Engineering Laboratories/SEL-2245-4-AC-Metering-Module.yml, module-types/Schweitzer Engineering Laboratories/sel-2243-power-coupler.yml, module-types/Schweitzer Engineering Laboratories/sel-2244-5-fast-high-current-digital-output-module.yml, module-types/Schweitzer Engineering Laboratories/sel-2245-2-dc-analog-input-module.yml, module-types/Schweitzer Engineering Laboratories/sel-2245-22-dc-analog-input-extended-range-module.yml, module-types/Schweitzer Engineering Laboratories/sel-2245-411-standard-current-and-low-voltage-(lea)-monitoring-module.yml, module-types/Supermicro/AOC-MCX4121A-ACAT.yaml, tests/definitions_test.py
Correcting non-ascii characters and test issues
=> Correction - ASCII and Tests

device-types/APC/AP8858.yaml
=> APC ap8858

module-types/Supermicro/PWS-605P-1H.yml
=> Supermicro PWS-605P-1H PSU

module-types/FS/XL710BM1-4SP.yaml
Add FS XL710BM1-4SP network card based on X710-DA4
=> XL710BM1-4SP

module-types/Supermicro/PWS-861A-1R.yml
* Add module-type for the Supermicro PWS-861A-1R 800/860W power supply
=> Add module type PWS-861A-1R

device-types/HPE/Aruba-3810M-40G-8SR.yaml
Fixes netbox-community/devicetype-library#2675
=> Fix: Aruba-3810M-40G-8SR ports 1-8 incorrect type

device-types/Brocade/ICX-6450-48.yaml, device-types/Brocade/ICX-6610-24.yaml, device-types/Brocade/ICX-6610-48.yaml, device-types/Brocade/ICX-6610-48p.yaml, device-types/Brocade/ICX-7150-C12P.yaml, device-types/Brocade/ICX-7250-24.yaml, device-types/Brocade/ICX-7250-48.yaml, device-types/Brocade/ICX-7450-48.yaml
Added Airflow, Weight values, and POE types to several brocade switches that were missing them.
=> Updating brocade weights

device-types/Bachmann/Bachmann-9x-power-socket.yml
Please add the new device type.
=> Add Bachmann 9x power socket

device-types/Cisco/N3K-C3548P-10GX.yaml
Self-explanatory.
Regarding airflow, depending on the configuration (PSUs and fans) it is possible to have either front-to-rear or rear-to-front, so I'm not sure if I should put it in the yaml.
=> Cisco: Add N3K-C3548P-10GX

device-types/Brocade/ICX-7150-24P.yml
Like title says
values from https://www.commscope.com/globalassets/digizuite/61729-ds-icx-7150.pdf
=> added Brocade/Ruckus ICX7150-24P, PoE+ variant of the ICX7150-24

device-types/Arista/CCS-755.yaml, device-types/Arista/CCS-758.yaml, module-types/Arista/CCS-750-SUP100.yaml, module-types/Arista/CCS-750-SUP25.yaml, module-types/Arista/CCS-750X-48SX-LC.yaml, module-types/Arista/CCS-750X-48THP-LC.yaml, module-types/Arista/CCS-750X-48TP-LC.yaml, module-types/Arista/CCS-750X-48ZP-LC.yaml, module-types/Arista/CCS-750X-48ZXP-LC.yaml, module-types/Arista/PWR-3351-AC-RED.yaml
* CCS-755
* CCS-758
* CCS-750X-48SX-LC
* CCS-750X-48THP-LC
* CCS-750X-48TP-LC
* CCS-750X-48ZP-LC
* CCS-750X-48ZXP-LC
* PWR-3351-AC-RED
=> Add Arista CCS-750X device types and module types

device-types/APC/BX1500M.yaml
Adding APC BX1500M UPS Device Type
=> Apc bx1500m

device-types/Cisco/C9300X-48TX.yaml
...which is basically HX that's already present, but does not have PoE
=> feat: add Cisco C9300X-48TX

device-types/Apple/A1991.yaml, device-types/Apple/A2304.yaml
See
- https://support.apple.com/en-us/118461
- https://support.apple.com/en-us/111907
=> Add Apple Mac Pro 2019

device-types/Cisco/ISR-1111-8P.yaml
Source: https://itprice.com/cisco/c1111-8p.html
=> fix: maximum draw of ISR 1111-8P

device-types/TP-Link/EAP683-LR.yaml
See https://www.omadanetworks.com/us/business-networking/omada-wifi-ceiling-mount/eap683-lr
=> Add TP-Link EAP683 LR

module-types/Supermicro/PWS-920P-SQ.yml
PWS-920P-SQ version of supermicro PSU
=> Add 920W version of common supermicro PSU

device-types/Cisco/C9200L-24P-4G.yaml
- There is no PoE on uplink ports
- Add weights
=> C9200L-24P-4G Enhancements

device-types/Cisco/N9K-C9332D-GX2B.yaml
Fixed some typo's in the Cisco Nexus 9332D-GX2B and added the Weight
=> Fix cisco n9k

module-types/Dell/0W1R7V.yml
=> Added Dell 0W1R7V module

module-types/Dell/CF4P0.yaml
two-port SFP+ 10g card for dell's LOM slot
=> Add Dell CF4P0 LOM NIC

device-types/ARRIS/S33v2.yml
Added the ARRIS S33v2 cable modem
=> Arris-s33v2

device-types/Supermicro/SuperServer-1028R-WTR.yml
https://www.supermicro.com/en/products/system/1U/1028/SYS-1028R-WTR.cfm
=> Added SuperServer 1028R-WTR

device-types/Cisco/C9200CX-12T-2X2G.yaml, device-types/Extreme Networks/X250e-48tDC.yaml, device-types/Extreme Networks/X440-48tDC.yaml, device-types/Fortinet/FAP-C24JE.yaml, device-types/Fortinet/FG-300D.yaml, device-types/Juniper/EX4200-24F.yaml, device-types/Juniper/EX4200-24P.yaml, device-types/Juniper/EX4200-24PX.yaml, device-types/Juniper/EX4200-24T.yaml, device-types/Juniper/EX4200-48P.yaml, device-types/Juniper/EX4200-48PX.yaml, device-types/Juniper/EX4200-48T.yaml, device-types/Riverbed/CX555.yaml, device-types/SNR/S2995G-24FX.yaml, device-types/SNR/S2995G-24TX-RPS.yaml, device-types/SNR/S2995G-24TX-UPS.yaml, device-types/Sophos/XGS-107.yaml, device-types/Sophos/XGS-108.yaml, module-types/CyberPower/RMCARD205.yaml, module-types/Extreme Networks/XN-DCPWR-300W-BF.yaml, module-types/Extreme Networks/XN-DCPWR-300W-FB.yaml
Improve device info by replacing other interface types
=> Improve data

README.md, rack-types/HPE/10622-G2.yaml, rack-types/HPE/10636-G2.yaml, rack-types/HPE/10642-G1.yaml, rack-types/HPE/10642-G2.yaml, rack-types/HPE/10648-G2.yaml, rack-types/HPE/10842-G1.yaml, rack-types/HPE/10842-G2.yaml, rack-types/HPE/10848-G2.yaml, rack-types/Hyperline/TTC-4266-SR-RAL9004.yaml, rack-types/Hyperline/TWB-1866-SR-RAL9004.yaml, rack-types/MetalBox/MQ426010.yaml
=> pre-commit run

device-types/Fortinet/FS-148F.yaml
Added the FortiSwitch 148F (which is almost the same as the POE versions).
=> added FortiSwitch 148F

device-types/Accedian/MetroNID-TE.yaml, device-types/Accedian/metroNID.yaml
Added the Accedian MetroNID TE.
=> Added MetroNID

device-types/Eaton/Tripp-Lite-B096-032.yaml, device-types/Eaton/Tripp-Lite-B097-016.yaml, device-types/Eaton/Tripp-Lite-B097-048.yaml
Added Eaton TrippLite B097-048 and  missing datasheet links for similar models.
=> Added Eaton TrippLite B097-048

device-types/RuggedCOM/RS900.yaml
Added RuggedCOM RS900 with 8 100base-tx and 1 100base-fx.
=> Added RuggedCOM RS900

module-types/FS/FHD-1MTP6LCDOM4A.yaml, module-types/FS/FHD-1MTP6LCDOM4AF.yaml
Add FS.com FHD-1MTP6LCDOM4AF & FHD-1MTP6LCDOM4A MPO casettes.
=> Add FS.com FHD-1MTP6LCDOM4AF & FHD-1MTP6LCDOM4A MPO casettes.
