netbox-community/devicetype-library

device-types/Juniper/MX10003-BASE.yaml
device-types/Juniper/MX10003-PREMIUM.yaml

Add both chassis configurations as sold by Juniper.
Note: They are both the same chassis, the -PREMIUM bundle just has more components installed by the factory. As they are separate SKUs I included both configurations.

Add Juniper MX10003 chassis

---

device-types/Juniper/QFX5110-48S-4C.yaml

Juniper automatically renames interfaces based on the transceiver installed. A 10G `xe-` port will therefore automatically be renamed to `ge-` the moment a 1G transceiver is plugged in. I included the default names for transceivers with the maximum speed installed, assuming that someone who buys an 48x10G switch will actually use it as 10G.

Add Juniper QFX5110-48S-4C

---

device-types/Juniper/MX204.yaml

Add device type for Juniper MX204 router (4 QSFP and 8 SFP+).

Add Juniper MX204 router

---

device-types/Juniper/MX104-BASE.yaml
device-types/Juniper/MX104-PREMIUM.yaml

This PR adds two new device types for MX104 BASE and PREMIUM chassis.
Note that a MX104 is not actually a 4U device, it's 3.5U (thanks Juniper). 4U seems the better matching usable height value given the circumstances.

Add Juniper MX104 chassis

---

device-types/Fortinet/FG-100F.yaml
device-types/Fortinet/FG-101F.yaml
device-types/Fortinet/FG-1100E.yaml
device-types/Fortinet/FG-1101E.yaml
device-types/Fortinet/FG-300E.yaml
device-types/Fortinet/FG-301E.yaml
device-types/Fortinet/FG-600E.yaml
device-types/Fortinet/FG-601E.yaml

Followed the approach of the Catalyst series devices that specify the name (FortiGate 80E) for the model var and the actual part number (FG-80E) for the part_number var.

Updated existing FortiGate model & part_number

---

device-types/Cisco/ISR4331.yaml

Cisco ISR4331 added missing usb-mini-b console-port

Cisco ISR4331 added missing usb-mini-b console-port

---

device-types/Cisco/ws-c3560cx-12pc-s.yaml
device-types/Cisco/ws-c3560cx-12pd-s.yaml
device-types/Cisco/ws-c3560cx-12tc-s.yaml
device-types/Cisco/ws-c3560cx-8pc-s.yaml
device-types/Cisco/ws-c3560cx-8pt-s.yaml
device-types/Cisco/ws-c3560cx-8tc-s.yaml
device-types/Cisco/ws-c3560cx-8xpd-s.yaml

The seemingly off ordering on the 3560-CX-8XPD-S corresponds to the
actual ordering of the OS output in the interface list.
Signed-off-by: Felix Kaechele <fkaechel@cisco.com>

Add Cisco Catalyst 3560CX series

---

device-types/Juniper/EX2300-C-12P.yaml
device-types/Juniper/EX2300-C-12T.yaml

Adding support for the EX2300-C-12P and 12T (PoE and Non PoE)
Spec sheet: https://www.juniper.net/assets/us/en/local/pdf/datasheets/1000580-en.pdf

Add Juniper EX2300-C-12P/T

---

device-types/Cisco/ws-c2960x-48fps-l.yaml

GigabitEthernet1/0/39 was marked as an SFP port, but it is a 1000base-t port

Correct interface GigabitEthernet1/0/39

---

device-types/Arista/DCS-7150SC-64.yaml
device-types/Arista/DCS-7280SR2-48YC6.yaml

Removed duplicate keys "is_full_depth" and added "part_number".

Fix Arista duplicate keys: DCS-7150SC-64

---

device-types/Infoblox/IB-1410.yaml
device-types/Infoblox/IB-1420.yaml
device-types/Infoblox/TE-1415-NS1GD-AC.yaml
device-types/Infoblox/TE-815-NS1GD-AC.yaml

Created 4 devicetypes for Infoblox:
- IB-1410
- IB-1420
- TE-1415-NS1GD-AC
- TE-815-NS1GD-AC

Infoblox add device-types

---

device-types/FS/FMU-1UFMX-N.yaml
device-types/FS/FMU-MC082745.yaml

Hi!
This PR adds
- FS.com 2-Slot 1U Rack-Chassis FMU-1UFMX-N
- FS.com 8Ch CWDM MUX 1270-1450 (Skip 1390,1410) FMU-MC082745
The PR uses manufacturer "FS". Other options would be "FS.com" or "Fibrestore". All options have pros and cons. If you have opinions on the manufacturer, please let me know.
Best
Max

Add FS.com CWDM 8Ch MUX + Chassis

---

device-types/Netonix/WS-24-400A.yaml

This device has 4 dual-purpose ports (21-24) which can be 1000BaseT or SFP. I chose to model them as 1000BaseT as the default.
Are there any guidelines about that? Is there a better way?

Add Netonix WISP switch WS-24-400A

---

device-types/Cisco/C1000-24P-4X-L.yaml

Adding support for Cisco Cisco C1000-24P-4X-L switch, schema doesn't currently support noting interfaces which support PoE.

Add Cisco C1000-24P-4X-L switch

---

device-types/Palo Alto/PA-5220.yaml
device-types/Palo Alto/PA-5250.yaml
device-types/Palo Alto/PA-5260.yaml
device-types/Palo Alto/PA-5280.yaml

Some fixes to the existing Palo Alto 5200 series device type definitions.
Contributing guidelines referenced:
* Name components exactly as they appear in the device's operating system (as opposed to the physical chassis label, if different).
* Use the complete form of interface names where applicable. For example, use TenGigabitEthernet1/2/3 instead of Te1/2/3.
* Avoid encapsulating YAML values in quotes unless necessary to avoid a syntax error.
Fixes made in this PR:
* renamed components and interfaces to match what the device's cli shows (used a PA-5220 to get this information)
* remove single quotes from interface names
* updated maximum and allocated draw from PA-5200 series datasheet
* changed some interface types based on PA-5200 series datasheet

Palo Alto 5200 series fixes

---

device-types/Juniper/EX2300-C-12P.yaml
device-types/Juniper/EX2300-C-12T.yaml

Both the RJ-45 and USB consoles were named "Console" which causes NetBox to throw an error on import.
This fixes #173, though it'd still be good to extend tests to check for this.

Give Juniper EX2300 console ports unique names

---

device-types/Aruba/Aruba7030.yaml
device-types/Aruba/Aruba7210.yaml
device-types/Aruba/Aruba7220.yaml
device-types/Aruba/ArubaMM-HW-10K.yaml
device-types/Aruba/ArubaMM-HW-1K.yaml
device-types/Aruba/ArubaMM-HW-5K.yaml

Adding device templates for Aruba wireless controllers (7030, 7210, 7220) and Hardware Mobility Masters (1,5,&10k)

Aruba 7000 & MobilityMaster

---

device-types/Aruba/Aruba2530-24G-PoEP.yaml
device-types/Aruba/Aruba2530-48G-PoEP.yaml
device-types/Aruba/Aruba2530-8G-PoEP.yaml

Add a description file for an Aruba 2530 48G-PoEP switch (48 ports BaseT, 4 ports SFP, 1 console port, 1 power supply)
Add a description file for an Aruba 2530 24G-PoEP switch (24 ports BaseT, 4 ports SFP, 1 console port, 1 power supply)
Add a description file for an Aruba 2530 8G-PoEP switch (8 ports BaseT, 2 dual-personnality ports RJ45/SFP, 1 console port, 1 power supply)

Aruba 2530

---

device-types/Ubiquiti/us-16-150w.yaml
device-types/Ubiquiti/us-24-500w.yaml
device-types/Ubiquiti/us‑24‑250w.yaml
device-types/Ubiquiti/us‑24‑500w.yaml
device-types/Ubiquiti/us‑48‑500w.yaml
device-types/Ubiquiti/us‑48‑750w.yaml

Added definitions for current Unifi generation 1 switches. These are distinct models from the Ubiquiti EdgeSwitches

Ubiiquiti unifi

---

device-types/Juniper/ACX1100-AC.yaml

This PR adds device type for [Juniper Networks ACX1000 Universal Metro Router](https://www.juniper.net/us/en/products-services/routing/acx-series/acx1000/), or more specifically it's AC version. It would be great to add DC version as well, but I'm not sure how to represent DC termination block connector as a Netbox power port.

Add Juniper ACX1100-AC

---

device-types/Ubiquiti/er-x.yaml

Adds support for the [Ubiquiti ER-X](https://www.ui.com/edgemax/edgerouter-x/)
Passes pytest on my local machine as GitHub Actions and branches don't play well with each other.

Add Device Type for the Ubiquiti ER-X

---

device-types/Dell/Networking_S4048-ON.yaml

In the existing Dell S4048 template, the ports TenGigabitEthernet 1/10, TenGigabitEthernet 1/20, TenGigabitEthernet 1/30, and TenGigabitEthernet 1/40 are not in the template. This added them in

Dell S4048 - Added missing TenGigabitEthernet ports (10,20,30,40)

---

device-types/APC/AP9617.yaml
device-types/APC/AP9618.yaml
device-types/APC/AP9619.yaml
device-types/APC/AP9630.yaml
device-types/APC/AP9631.yaml
device-types/APC/AP9640.yaml
device-types/APC/AP9641.yaml

Add APC SmartUPS management cards generation 1,2,3 that can be inserted into various models of UPS.  Separately someone may wish to define different rack mount UPS models that these devices could be installed in for DCIM purposes, but this is enough to track the network device and its config.

Add APC SmartUPS Management cards

---

device-types/Alpha/CXC.yaml
device-types/Alpha/CXCM1-HP.yaml

Add new Alpha vendor and Cordex DC plant management cards that slot into UPS equipment.  Did not yet add the rack mounted hardware these management modules slot into, which would be useful for DCIM, but this is enough to model the networked device.

Add Alpha Cordex DC plant management controllers

---

device-types/Cisco/N2K-2248TP-E-1GE.yaml
device-types/Cisco/N2K-C2232PP-10GE.yaml
device-types/Cisco/N2K-C2232TM-E-10GE.yaml
device-types/Cisco/N2K-C2248PQ.yaml

Add Cisco Nexus 2000 fabric extenders.  Ports will likely always need to be renamed as the FEX numbers start at slot 100 IIUC, eg. Ethernet101/1/1 instead of Ethernet1/1/1
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-2000-series-fabric-extenders/data_sheet_c78-507093.html

Add Nexus fabric extenders

---

device-types/Raspberry Pi/RPI3-MODB-1GB.yaml
device-types/Raspberry Pi/RPI3-MODBP-1GB.yaml
device-types/Raspberry Pi/RPI4-MODBP-1GB.yaml

I'm not sure this is useful for everyone, but we are using Raspberry Pi devices as network probes, if that is common enough then maybe it can be in the library and if that is out of scope then we can keep it in our fork.

Add Raspberry Pi models for utility devices

---

device-types/F5/BIG-IP_3900.yaml
device-types/F5/BIG-IP_4200v.yaml
device-types/F5/BIG-IP_5200v.yaml
device-types/F5/BIG-IP_VPR-C2400.yaml
device-types/F5/BIG-IP_i4600.yaml
device-types/F5/BIG-IP_i4800.yaml
device-types/F5/BIG-IP_i5800.yaml

Add some F5 BIG-IP models:
- BIG-IP 3900
- BIG-IP 4200v
- BIG-IP 5200v
- BIG-IP i4600
- BIG-IP i4800
- BIG-IP i5800
- BIG-IP Viprion C2400 Chassis

Add various F5 BIG-IP models

---

device-types/Cisco/C9500-32QC.yaml
device-types/Cisco/ISR3945.yaml
device-types/Cisco/c9300-24p.yaml
device-types/Cisco/c9300-24t.yaml
device-types/Cisco/c9300-48p.yaml
device-types/Cisco/c9300-48t.yaml
device-types/Cisco/c9300-48uxm.yaml
device-types/Cisco/ws-c2960x-24td-l.yaml
device-types/Cisco/ws-c2960x-48td-l.yaml
device-types/Cisco/ws-c2960xr-48fpd-i.yaml
device-types/Cisco/ws-c2960xr-48fps-i.yaml
device-types/Cisco/ws-c2960xr-48lpd-i.yaml
device-types/Cisco/ws-c2960xr-48lps-i.yaml
device-types/Cisco/ws-c2960xr-48td-i.yaml
device-types/Cisco/ws-c2960xr-48ts-i.yaml
device-types/Cisco/ws-c3650-48fq-e.yaml
device-types/Cisco/ws-c3650-48fq-s.yaml
device-types/Cisco/ws-c3650-48pq-e.yaml
device-types/Cisco/ws-c3650-48pq-s.yaml
device-types/Cisco/ws-c3650-48tq-e.yaml

Added some new and old Cisco models. Fixed a couple others.
- Added C9300-48t
- Fixed other C9300s PWR and mgmt interface names
- Added some C2960 variants
- Added some C3650 variants
- Added ISR3945

Add and fix various Cisco models

---

device-types/Aruba/Aruba2920-24G.yaml
device-types/Aruba/Aruba2920-48G-PoEP.yaml
device-types/Aruba/Aruba2920-48G.yaml
device-types/Aruba/Aruba2930F-48G-4SFPP.yaml
device-types/Aruba/Aruba7005.yaml
device-types/Aruba/Aruba7010.yaml
device-types/Aruba/Aruba7205.yaml
device-types/HPE/ProCurve-2810-24G.yaml
device-types/HPE/ProCurve-2810-48G.yaml

Add some Aruba controllers and switches. Also added a couple legacy ProCurve HP switches.
- 2920-24G
- 2920-48G-PoE+
- 2920-48G
- 2930F-48G-4SFP+
- Aruba7005
- Aruba7010
- Aruba7205
- ProCurve 2810-24G
- ProCurve 2810-48G

Add various Aruba and legacy HPE devices

---

device-types/Cisco/ISR2921.yaml

My ISR2921 interfaces don't have the subslot. Changing to just 0/0, 0/1, and 0/2.
```
#show inventory 
NAME: "CISCO2921/K9", DESCR: "CISCO2921/K9 chassis, Hw Serial#: redacted, Hw Revision: 1.0"
PID: CISCO2921/K9      , VID: V08 , SN: redacted
```
```
#show interfaces description 
Interface                      Status         Protocol Description
Em0/0                          admin down     down     
Gi0/0                          up             up       
Gi0/1                          up             up       
Gi0/2                          up             up       
```

Fix interface slots for ISR2921

---

device-types/Dell/PowerEdge_R620.yaml
device-types/Dell/PowerEdge_R630.yaml
device-types/Dell/PowerEdge_R640.yaml
device-types/Dell/PowerEdge_R720.yaml
device-types/Dell/PowerEdge_R730.yaml
device-types/Dell/PowerEdge_R740.yaml

Only the R720 was included in the existing community definitions. The additional servers are nearly identical.
While working on this, I made a few other alterations:
- Changed "IDRAC" to Dell's capitalization, "iDRAC"
- Changed filename from "R720" to "PowerEdge_R720" to include the entire product name in the filename.
As a note, Dell servers are a bit odd and don't have public part numbers that I could find, so there's no straightforward way to identify "R630 with 8 2.5" drives" that doesn't get needlessly wordy. This is almost never significant, except in the case of models like the R630 with 10 2.5" disks, which forgoes one of the front USB ports. I chose to use one YAML file for each model since there's no standard way to denote a LFF, SFF, etc variant for Dell servers. For users with …

Add additional Dell server products

---

device-types/TrippLite/ULTRABLOK428.yaml

The manufacturer for ULTRABLOK428 was set to "TrippLite" while all other Tripp-Lite devices are spelled "Tripp-Lite" in their YAML files. For consistency, this change alters the spelling to match the other Tripp-Lite products.

Change manufacturer for ULTRABLOK428

---

device-types/APC/AP8953.yaml

New devicetype for APC AP8953 PDU.  Same as 8941, but has different input.

added devicetype for apc-ap8953

---

device-types/Aruba/ArubaMC-3400.yaml

Add device-type for Aruba Mobility controller 3400 (4 ports gig0/0/0 to 0/0/3 dual personnality (Base T or Base X), 1 console port, 1 power supply)

Add device-type for Aruba Mobility controller 3400

---

device-types/Aruba/ArubaMC-3200.yaml

Add device-type for Aruba Mobility controller 3200 (4 ports gig0/0/0 to 0/0/3 dual personnality (Base T or Base X), 1 console port, 1 power supply)

Add device-type for Aruba Mobility controller 3200

---

CONTRIBUTING.md

Create draft first instead of submitting PR, tests will be re-run when changes are made before submitting.

Update CONTRIBUTING.md to create draft PR before submitting

---

device-types/Cisco/WS-C4510R+E.yaml

Device has more HRU. Source: https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-4500-series-switches/product_data_sheet0900aecd801792b1.html

Device has 14 HRU not 11

---

device-types/Dell/PowerEdge_R620.yaml
device-types/Dell/PowerEdge_R630.yaml
device-types/Dell/PowerEdge_R640.yaml
device-types/Dell/PowerEdge_R720.yaml
device-types/Dell/PowerEdge_R730.yaml
device-types/Dell/PowerEdge_R740.yaml

The Dell PowerEdge definitions contain a duplicate `console-server-ports` key to separate front/rear ports. This results in only the rear ports being imported into NetBox.
Removing this duplicate key resolves the issue.

Remove duplicate console-server-ports key

---

device-types/Cisco/N9K-C93108TC-FX.yaml

This pull request renames the Nexus 93108TC-FX. It removes "Chassis" from the title since it isn't a chassis. Also, it removes the prefix of "Nexus9000" in favor of Nexus since 9000 is redundant since the model number is listed. Finally, it removes the C in front of the 93108 model number.

Rename 93108TC to be more consistent with other systems

---

device-types/Cisco/cdb-8p.yaml
device-types/Cisco/cdb-8u.yaml

This is a child device, so the height must be zero, otherwise the import will fail

fix Cisco cdb devices

---

device-types/Juniper/MX480.yaml

Removed the power supplies as these are modular and have different power draws, ac/dc, etc.
Removed the console ports.  No guarantee that someone has two REs installed.
Based on the [NetBox documentation](https://netbox.readthedocs.io/en/stable/core-functionality/device-types/) networking gear with line cards should not be modeled as parent/child.
> This parent/child relationship is not suitable for modeling chassis-based devices, wherein child members share a common control plane. Instead, line cards and similarly non-autonomous hardware should be modeled as inventory items within a device, with any associated interfaces or other components assigned directly to the device.

Should Not Be a Parent, Removed Power Supplies & Console Ports

---

device-types/Juniper/EX2200-C-12P.yaml
device-types/Juniper/EX2200-C-12T.yaml
device-types/Juniper/SRX210HE2.yaml

Adding a couple devices I have at home
* EX2200-C-12P
* EX2200-C-12T
* SRX210HE2
For the SRX210HE2, I was a little unsure what to put for the power type, as it has an external 12v power supply, but in `show chassis hardware` you have Power Supply 0

Juniper: add EX2200-C-12P, EX2200-C-12T, SRX210HE2

---

device-types/MikroTik/RB750Gr3.yaml

This PR adds MikroTik RB750Gr3. Product page https://mikrotik.com/product/RB750Gr3. Technically this model is identical to already present RB750r3, but RB750r3 seems to be discontinued for I was even unable to find it's product page.

Add MikroTik RB750Gr3

---

device-types/Brocade/icx7150-c12.yaml

Using the naming convention built into Netbox (`ge-`, `xe-`, etc), which happens to match Cisco's.  I haven't ever seen "GigabitEthernet1/2" on any Brocade/Ruckus equipment.
Also, previous Brocade switches were named 1/1, 1/2, 1/3.  All switches I've seen in 6450, 6610, 7150, 7250, and 7450 all use the 1/1/1, 1/1/2 convention.  So, I'm using that here as well (which further matches Netbox's suggestions in the UI).
---
This switch has 12x 1-Gbps PoE+ ports, 2x 1-Gbps Uplink ports (assignable), and 2x 10-Gbps Upline SPF+ ports, along with an 1-Gbps management port and 1 console port.

Add Brocade ICX7150-C12P

---

README.md

Running the `pre-commit --all` script removes two trailing spaces from the current README.md file, and adds a newline at the end.  The README.md file is then marked as changed.
This PR will merge those changes so that `pre-commit --all` is happy and doesn't change anything.
No other changes.

Include README changes made by pre-commit

---

device-types/TrippLite/SMART1500LCD.yaml

Add Tripplite SMART1500LCD UPS with info from [manufacturer info page](https://www.tripplite.com/smartpro-lcd-120v-1500va-900w-line-interactive-ups-avr-2u-rack-tower-lcd-usb-db9-serial-8-outlets~SMART1500LCD) and [datasheet](https://assets.tripplite.com/product-pdfs/en/smart1500lcd.pdf)

Add Tripplite SMART1500LCD UPS

---

device-types/Ubiquiti/U6-LR.yaml
device-types/Ubiquiti/UAP-FlexHD.yaml

Adds the U6-LR and UAP-FlexHD access point definitions.  Based on info from UI.com web site and the existing U6-Lite definition as a template.

Add two Ubiquiti access points

---

device-types/Aruba/2930F-24G-4SFPP.yaml
device-types/Aruba/2930F-24G-PoEP-4SFPP.yaml

Adds Aruba 2930F-24G-4SFP+ and 2930F-24G-PoE+-4SFP+ switch models.

Add Aruba 2930F 24-port models

---

README.md

This fixes all occurrences of "Netbox".
Ref: https://netbox.readthedocs.io/en/stable/development/style-guide/#branding

docs: NetBox should be referred to as NetBox

---

device-types/3Com/4210G-24_Port.yml
device-types/3Com/4210G-48_Port.yml
device-types/3Com/4210G-PWR-24_Port.yml

This PR adds 3Com 4210G family switches and fixes OBE error in 3Com 4200G-48 template.

Add 3Com 4210G family switches, fix OBE in 4200G-48

---

device-types/Aruba/2530-24G.yaml
device-types/Aruba/2530-48G.yaml
device-types/Aruba/2530-8G.yaml
device-types/Aruba/2920-24G-PoEP.yml

This PR adds non-PoE models from Aruba 2530 family and Aruba 2920-24G-PoEP.

Add Aruba 2530, 2920 family switches

---

device-types/Ubiquiti/USW-Lite-8-PoE.yaml

Adds a definition for the Ubiquiti USW-Lite-8-PoE based on the [UI web page](https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-lite-8-poe).

Add Ubiquiti USW-Lite-8-PoE

---

device-types/Rockwell Automation/1783-BMS06SA.yaml
device-types/Rockwell Automation/1783-BMS06SGA.yaml
device-types/Rockwell Automation/1783-BMS06SGL.yaml
device-types/Rockwell Automation/1783-BMS06SL.yaml
device-types/Rockwell Automation/1783-BMS06TA.yaml
device-types/Rockwell Automation/1783-BMS06TGA.yaml
device-types/Rockwell Automation/1783-BMS06TGL.yaml
device-types/Rockwell Automation/1783-BMS06TL.yaml
device-types/Rockwell Automation/1783-BMS10CA.yaml
device-types/Rockwell Automation/1783-BMS10CGA.yaml
device-types/Rockwell Automation/1783-BMS10CGL.yaml
device-types/Rockwell Automation/1783-BMS10CGN.yaml
device-types/Rockwell Automation/1783-BMS10CGP.yaml
device-types/Rockwell Automation/1783-BMS10CL.yaml
device-types/Rockwell Automation/1783-BMS20CA.yaml
device-types/Rockwell Automation/1783-BMS20CGL.yaml
device-types/Rockwell Automation/1783-BMS20CGN.yaml
device-types/Rockwell Automation/1783-BMS20CGP.yaml
device-types/Rockwell Automation/1783-BMS20CGPK.yaml
device-types/Rockwell Automation/1783-BMS20CL.yaml
device-types/Rockwell Automation/1783-BMS4S2SGA.yaml
device-types/Rockwell Automation/1783-BMS4S2SGL.yaml

This PR adds the default software virtual interface for all variants of the stratix 5700 switches.

Add default SVI to RA Stratix 5700 Switches

---

device-types/Arista/DCS-7050TX3-48C8.yaml

The title and product name is DCS-7050TX3-48C8 but `part-number` and `model` are set with DDCS-7050TX3-48C8.
This PR tend to fix the typo

Update part-number for Arista DCS-7050TX3-48C8

---

device-types/Panduit/FRME4.yaml

This adds the Panduit FRME4 Rack Mount Fiber Enclosure.  All bays are lettered.
https://www.panduit.com/en/products/fiber-optic-systems/fiber-optic-panels-cassettes-enclosures/fiber-optic-enclosures/frme4.html

Added Panduit FRME4

---

device-types/Dell/networking-s5232f-on.yaml

* The Dell S5232F-ON has 32 QSFP28 ports, 1/1/1-32 and 2 SFP+
ports, 1/1/33 and 1/1/34. The current template incorrectly lists
these two ports as QSFP28
https://www.delltechnologies.com/asset/en-us/products/networking/technical-support/dell_emc_networking-s5200_on_spec_sheet.pdf

Fixed port type to SFP+ for ports 33 and 34

---

tests/schema.json

Updates the schema.json for CI to accept the new Interface Type "IEEE 802.15.1 (Bluetooth)" .
Refers to my PR on the main netbox repository: [PR#7816](https://github.com/netbox-community/netbox/pull/7816)
Marking as draft until the PR in the main repo is merged.

Update CI for new Interface Type

---

device-types/Cisco/SG300-28.yaml

The Cisco SG300-28 is not full depth, but was falsely flagged as such

Correct Cisco SG300-28 depth

---

device-types/Ubiquiti/UAP-AC-LR.yaml

Adds Ubiquiti's [UAP-AC-LR](https://www.ui.com/unifi/unifi-ap-ac-lr/)
- Follows same format as similar UAP-AC-* devices.

Add Ubiquiti UAP-AC-LR

---

device-types/Juniper/QFX5120-48T.yaml

- 100G interfaces are named `et-*` in JunOS
- QFX5120-48T has six, not eight 100G QSFP28 interfaces

[QFX5120-48T] rename interfaces and cleanup extra interfaces

---

tests/schema.json

Rename optic type 128gfc-sfp28 to 128gfc-qsfp28 in schema.json. This was fixed in Netbox with v3.1.0 (https://github.com/netbox-community/netbox/issues/7589) and should fix schema.json for pull request #503

Rename optic type 128gfc-sfp28 to 128gfc-qsfp28

---

device-types/Ubiquiti/AF-5XHD.yml
tests/schema.json

Adding the Ubiquiti airFiber 5XHD
https://dl.ubnt.com/datasheets/airfiber/airFiber_5XHD_DS.pdf
Used ieee802.11ax as it doesn't allow wireless parameters to be specified despite the fact that it is a LTE-U device.
Has been tested to import fine into my v3.1.6 instance of netbox.

Add ubnt af 5xhd

---

.gitignore
device-types/Ubiquiti/UDM-Pro.yaml
device-types/Ubiquiti/USW-Aggregation.yaml
tests/schema.json

I was adding these two devices to a new NetBox install today and noticed a few discrepancies in the definitions.
**USW-Aggregation**
I was unable to find a 10-port version of this switch and the datasheet I found from 2020 only lists an 8-port variation, which is the only one I could find. I updated the device to only include 8 ports now.
**UDM-Pro**
The primary change here is to mark it as not a full-depth device. As long as I was updating it I thought I'd add the airflow and update the model name to match the data sheet's name and add the part number.
**Airflow Direction in Schema**
I added the "airflow" field to the device type schema. I added airflow direction to the UDM-Pro on a whim, so this was required to allow the tests to pass.
I may have more updates coming and I know I'll have …

Update Ubiquiti USW-Aggregation and UDM-Pro

---

device-types/Ciena/5170.yaml
device-types/Ciena/5171.yaml

Added device type definitions for Ciena 5170 and 5171. All Pre-commit scripts ran and passed: 
```
devicetype-library % pre-commit run --all                                                 
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check YAML files.........................................................Passed
Format YAML files........................................................Passed
Lint YAML files..........................................................Passed
```

Added device type definitions for Ciena 5170 and 5171

---

device-types/Cisco/C9606R.yaml
module-types/Cisco/C9600-LC-24C.yaml
module-types/Cisco/C9600-LC-48S.yaml
module-types/Cisco/C9600-LC-48TX.yaml
module-types/Cisco/C9600-LC-48YL.yaml
module-types/Cisco/C9600-SUP-1.yaml
module-types/Cisco/C9600X-SUP-2.yaml

Add Cisco Catalyst 9606R with the following modules
- C9600-LC-24C
- C9600-LC-48S
- C9600-LC-48TX
- C9600-LC-48YL
- C9600-SUP-1
- C9600X-SUP-2

Add Catalyst 9600 and modules

---

device-types/Juniper/SRX300.yaml
device-types/Juniper/SRX320.yaml
device-types/Juniper/SRX340.yaml
device-types/Juniper/SRX345.yaml

- include power draw
- include link to datasheet
- include height
- include full depth indicator
- use same attribute order for devices
I've left out srx380 in this as I'm not sure what the intention with that one was, its attributes are inconsistent with the rest of the series.

Update Juniper SRX 300-series devices

---

device-types/Allied Telesis/x8106.yaml
device-types/Allied Telesis/x8112.yaml
device-types/Allied Telesis/x908Gen2.yaml
module-types/Allied Telesis/SBx81CFC400.yaml
module-types/Allied Telesis/SBx81CFC960.yaml
module-types/Allied Telesis/SBx81GC40.yaml
module-types/Allied Telesis/SBx81GP24.yaml
module-types/Allied Telesis/SBx81GS24a.yaml
module-types/Allied Telesis/SBx81GT24.yaml
module-types/Allied Telesis/SBx81GT40.yaml
module-types/Allied Telesis/SBx81XLEM.yaml
module-types/Allied Telesis/SBx81XS16.yaml
module-types/Allied Telesis/SBx81XS6.yaml
module-types/Allied Telesis/SBxPWRPOE1.yaml
module-types/Allied Telesis/SBxPWRSYS1-DC.yaml
module-types/Allied Telesis/SBxPWRSYS1.yaml
module-types/Allied Telesis/SBxPWRSYS2.yaml

Add Allied Telesis modular switch platform x8100 with all corresponding products.
Also changed x908 Gen2 to use the PSUs of the x8100 platform.

Add Allied Telesis x8100 series

---

device-types/Raspberry Pi/RPI3-MODB-1GB.yaml
device-types/Raspberry Pi/RPI3-MODBP-1GB.yaml
device-types/Raspberry Pi/RPI4-MODB-1GB.yaml
device-types/Raspberry Pi/RPI4-MODB-2GB.yaml
device-types/Raspberry Pi/RPI4-MODB-4GB.yaml
device-types/Raspberry Pi/RPI4-MODB-8GB.yaml

This PR fixes a few issues with the raspberry pi devices.
* 1GB pi 4 renamed to match the other devices (there is no B+ variant of the pi4)
* Swapped power inputs types to correct USB connector for each variant
* Added Pi's wifi interfaces
* Fixed interface type for pi3 to 10/100

Raspberrypi device fixes

---

device-types/Peplink/Balance-1350.yaml
device-types/Peplink/Balance-305.yaml

Addition of Peplink 1350.
[Netbox-Device-Type-Library-Import](https://github.com/dmcken/Netbox-Device-Type-Library-Import) doesn't work with manufacturer name of PepLink vs Peplink so lower-cased the only other model under this manufacturer.

Add peplink 1350

---

device-types/APC/APTF10KT01.yaml
device-types/APC/SMT1000.yaml
device-types/APC/SMT1500.yaml
device-types/APC/SMT1500RM2U.yaml
device-types/APC/SMX2200HV.yaml
device-types/APC/SRT3000RMXLT.yaml
device-types/APC/SURT192RMXLBP2.yaml
device-types/APC/SURT20KRMXLT.yaml
module-types/APC/AP9617.yaml
module-types/APC/AP9618.yaml
module-types/APC/AP9619.yaml
module-types/APC/AP9630.yaml
module-types/APC/AP9631.yaml
module-types/APC/AP9640.yaml
module-types/APC/AP9641.yaml

I opened Issue #821 because I think APC NMC modules are better modeled as modules than devices now that NetBox supports them. This pull request includes that conversion, as well as some new APC device models that support these modules.

add some APC UPS, XLBP, XFMR device models, convert NMC from device to module models

---

device-types/Cisco/FPR1120-NGFW-K9.yaml

The USB console port is mini B. (The USB A port on the device is a host port and NOT a console port).

Fix firepower 1120 console port

---

device-types/Zyxel/XGS1930-28.yaml
device-types/Zyxel/XGS1930-28HP.yaml
device-types/Zyxel/XGS1930-52.yaml
device-types/Zyxel/XGS1930-52HP.yaml

add XGS1930-28, XGS1930-28HP, XGS1930-52, XGS1930-52HP switches
[XGS1930 series specs](https://www.zyxel.com/products_services/24-48-port-GbE-Smart-Managed-Switch-with-4-SFP--Uplink-XGS1930-Series/specifications)

Add Zyxel XGS1930 smart managed switch family

---

device-types/Cisco/C9200-24P.yaml
device-types/Cisco/C9200-24T.yaml
device-types/Cisco/C9200-48P.yaml
device-types/Cisco/C9200-48T.yaml
device-types/Cisco/C9200L-24P-4G-E.yaml
device-types/Cisco/C9200L-24P-4G.yaml
device-types/Cisco/C9200L-24P-4X.yaml
device-types/Cisco/C9200L-24T-4G.yaml
device-types/Cisco/C9200L-24T-4X.yaml
device-types/Cisco/C9200L-48P-4G-E.yaml
device-types/Cisco/C9200L-48P-4G.yaml
device-types/Cisco/C9200L-48P-4X.yaml
device-types/Cisco/C9200L-48PL-4G.yaml
device-types/Cisco/C9200L-48T-4G.yaml
device-types/Cisco/C9200L-48T-4X.yaml
device-types/Cisco/C9300L-24P-4G.yaml
device-types/Cisco/C9300L-48P-4G.yaml
device-types/Cisco/C9300L-48P-4X.yaml
device-types/Cisco/C9300L-48UXG-4X.yaml
device-types/Cisco/WS-C3750E-24TD.yaml

Fix all instances of STACK# to Stackport1/(#+1)

Cisco Stackport Name Changes

---

device-types/Cisco/Meraki-MS250-24.yaml
device-types/Cisco/Meraki-MS250-24P.yaml
device-types/Cisco/Meraki-MS250-48.yaml
device-types/Cisco/Meraki-MS250-48LP.yaml
module-types/Cisco/Meraki-MA-PWR-1025WAC.yaml
module-types/Cisco/Meraki-MA-PWR-250WAC.yaml
module-types/Cisco/Meraki-MA-PWR-640WAC.yaml

I'm not entirely sure about the PSU config, but it seems that this is also being done this way for some other devices already.
One PSU is bundled with the switch and a second one can be installed for redundancy.
There's no requirement to always have a specific one, as long as at least one is present.
Both of them are modular.

Add/update Cisco Meraki MS250 switches and associated PSUs

---

device-types/Eaton/9PX3000iRT2U.yaml
device-types/Eaton/9PXEBM72RT2U.yaml
device-types/Eaton/EMPDT1H1C2.yaml
module-types/Eaton/EMPDT1H1C2.yaml
module-types/Eaton/Network-M2.yaml

Adds device modules for:
- UPS: 9PX 3000i RT 2U (9PX3000iRT2U)
- Network module: Network-M2 (744-A3983-02)
- Environment sensor: Environmental Monitoring Probe Gen 2 (EMPDT1H1C2)
- Battery extension module: 9PX Extended Battery Module, 72V (9PXEBM72RT2U)

Add Eaton UPS 9PX and related devices/modules

---

device-types/SonicWall/NSa2650.yaml
device-types/SonicWall/NSa2700.yaml
device-types/SonicWall/NSa3650.yaml
device-types/SonicWall/NSa3700.yaml
device-types/SonicWall/NSa4650.yaml
device-types/SonicWall/NSa4700.yaml
device-types/SonicWall/NSa5650.yaml
device-types/SonicWall/NSa6700.yaml
device-types/SonicWall/NSsp13700.yaml
device-types/SonicWall/NSsp15700.yaml
module-types/SonicWall/01-SSC-0019.yaml
module-types/SonicWall/01-SSC-1215.yaml
module-types/SonicWall/02-SSC-3078.yaml
module-types/SonicWall/02-SSC-3114.yaml
module-types/SonicWall/02-SSC-3115.yaml
module-types/SonicWall/02-SSC-3116.yaml
module-types/SonicWall/02-SSC-3117.yaml
module-types/SonicWall/02-SSC-8060.yaml
module-types/SonicWall/02-SSC-8061.yaml
module-types/SonicWall/02-SSC-8893.yaml
module-types/SonicWall/02-SSC-8894.yaml

Modify all existing SonicWall products which can hold modules or inventory items of any type.
Additionally, add PSU/Storage modules which can be placed in modules.

Modify SonicWall modular products

---

module-types/Ubiquiti/RPS-AC-100W.yaml

AC Power supply used in Ubnt OLTs and routers.

Add ubnt rps ac 100w

---

schema/components.json

Adding Power-over-Ethernet attributes to component definition.  
This enables contributors to enrich devices and modules with information about PoE-capable ports.

Add PoE (mode/type) to component definition

---

device-types/Dell/PowerEdge_R940.yaml

Dell R940 is 3U, not 4U. Can't find any examples of a 4U PowerEdge R940.
References:
- https://i.dell.com/sites/doccontent/shared-content/data-sheets/en/Documents/poweredge-r940-spec-sheet.pdf
- https://www.dell.com/en-us/shop/dell-poweredge-servers/poweredge-r940-rack-server/spd/poweredge-r940/pe_r940_12229_vi_vp

Dell R940 is 3U, not 4U

---

device-types/Dell/PowerEdge_R740xd.yaml

Dell R740xd is 2U, not 1U. Couldn't find any reference to a 1U 740xd on Dell's website, and I haven't run across a 1U 740xd in the wild.
References:
- https://i.dell.com/sites/csdocuments/Shared-Content_data-Sheets_Documents/en/poweredge-r740xd-spec-sheet.pdf
- https://www.dell.com/en-us/shop/cty/pdp/spd/poweredge-r740xd/pe_r740xd_tm_vi_vp_sb

Dell R740xd is 2U, not 1U

---

device-types/PC Engines/APU.yaml
device-types/PC Engines/APU2.yaml
device-types/PC Engines/APU4.yaml

Add manufacturer: PC Engines.
Add models:
- APU
- APU2
- APU4

Add PC Engines manufacturer with APU models

---

device-types/Cisco/ASR1002-HX.yaml

The ASR1002-HX TenGigabitEthernet interfaces are numbered TenGigabitEthernet0/1/X but the current devicetype is using TenGigabitEthernet0/0/X.
This PR fixes those interfaces to match what is in the Cisco Hardware Installation Guide and in the box.
ASR1002-HX CLI output:
```
ASR1002-HX# show int descr
Interface                      Status         Protocol Description
Gi0/0/0                        admin down     down     
Gi0/0/1                        admin down     down     
Gi0/0/2                        admin down     down     
Gi0/0/3                        admin down     down     
Gi0/0/4                        admin down     down     
Gi0/0/5                        admin down     down     
Gi0/0/6                        admin down     down     
Gi0/0/7                        admin …
```

Fix ASR1002-HX interfaces numbering for TenGigabitEthernet interfaces from TenGigabitEthernet0/0/X to TenGigabitEthernet0/1/X

---

device-types/AVM/7590.yaml

Added Comments Link, fixing Typos and correct ISDN Port Name and Airflow added.
Original File: https://github.com/netbox-community/devicetype-library/blob/master/device-types/AVM/7590.yaml

Updated Typos and added Details for AVM FRITZ!Box 7590

---

device-types/AVM/7530.yaml

Adds the [AVM Fritzbox 7530](https://avm.de/produkte/fritzbox/fritzbox-7530/technische-daten/), an extremely common home router in Germany. The sister product, 7590, is already in the device type library.

feat: add AVM Fritzbox 7530

---

device-types/APC/SMT3000RMI2UC.yaml
device-types/TP-Link/TL-SG105E.yaml
device-types/TP-Link/TL-SG108E.yaml

Sometimes when people forget to run `pre-commit run` there are slight formatting issues. We should really look at fixing these in the GitHub Actions, but for now here is another manual fix

Fixed formatting on newer files

---

device-types/Allied Telesis/MCR12.yaml
module-types/Allied Telesis/FS201.yaml
module-types/Allied Telesis/FS202.yaml
module-types/Allied Telesis/FS232-1.yaml
module-types/Allied Telesis/FS232-2.yaml
module-types/Allied Telesis/FS232.yaml
module-types/Allied Telesis/FS238A-1.yaml
module-types/Allied Telesis/FS238B-1.yaml
module-types/Allied Telesis/PWR4.yaml

Added the following Allied Telesis device/modules:
- MCR12
- FS201
- FS202
- FS232/1
- FS232/2
- FS232
- FS238A/1
- FS238B/1
- PWR4 (power module for the MCR12)

Allied Telesis MCR12 and Modules

---

module-types/Allied Telesis/PWR1200.yaml
module-types/Allied Telesis/PWR250.yaml
module-types/Allied Telesis/PWR4.yaml
module-types/Allied Telesis/PWR600-80.yaml
module-types/Allied Telesis/PWR600.yaml
module-types/Allied Telesis/PWR800.yaml

Updated the power modules to include their use/details from Allied Telesis. Updated PWR4 to more closely match the name printed on the unit, also added the max draw.

Allied Telesis Power Module Updates

---

module-types/Allied Telesis/FS201.yaml
module-types/Allied Telesis/FS202.yaml
module-types/Allied Telesis/FS232-1.yaml
module-types/Allied Telesis/FS232-2.yaml
module-types/Allied Telesis/FS232.yaml
module-types/Allied Telesis/FS238A-1.yaml
module-types/Allied Telesis/FS238B-1.yaml
module-types/Allied Telesis/SBx81CFC400.yaml
module-types/Allied Telesis/SBx81CFC960.yaml

I updated the Allied Telesis modules to include their slot number in the name for easier identification

Update Allied Telesis modules to include their slot number 

---

device-types/Dell/PowerVault_ME4024.yml
module-types/Dell/3PD98.yaml
module-types/Dell/49H29.yaml

Fixed the ME4024 to have module bays for the swappable PSU and controllers

PowerVault ME4024 Fix

---

module-types/Dell/49H29.yaml

Fixed serial name for Dell 49H29 SAS 4 port controller

Dell 49H29 Serial Name Fix

---

device-types/NEC/UNIVERGE-IX2106.yaml
device-types/NEC/UNIVERGE-IX2107.yaml
device-types/NEC/UNIVERGE-IX2215.yaml
device-types/NEC/UNIVERGE-IX2235.yaml
device-types/NEC/UNIVERGE-IX2310.yaml

This PR introduces (current mainline) UNIVERGE IX Series manufactured by NEC.
The catalogue can be downloaded from following link (Please note that the documentation published there are all written in Japanese):
- https://jpn.nec.com/univerge/ix/download.html
-----
Signed-off-by: KOSHIKAWA Kenichi <reishoku.misc ~@~ pm.me>

Addition of NEC UNIVERGE IX Series

---

device-types/Ubiquiti/USW-Pro-Aggregation.yaml
schema/components.json

This PR introduces Ubiquiti Switch Pro Aggregation and `ubiquiti-smartpower` Power Connector.
Datasheet (Direct Link, PDF): https://dl.ui.com/ds/usw-pro-aggregation_ds.pdf
Related Issue in netbox-community/netbox:
- https://github.com/netbox-community/netbox/issues/9192
- https://github.com/netbox-community/netbox/issues/9343
-----
Signed-off-by: KOSHIKAWA Kenichi <reishoku.misc ~@~ pm.me>

Addition of Ubiquiti Switch Pro Aggregation

---

device-types/Supermicro/AS-1114S-WN10RT.yml
device-types/Supermicro/AS-1123US-TR4.yml

I presume they were added by accident.

Remove spaces from Supermicro device names

---

schema/components.json

In JSON Schema, multipleOf has issues with precision and specifically has a rounding issue. As mentioned in this [jsonschema issue](https://github.com/python-jsonschema/jsonschema/issues/679) this can be fixed by using `multipleOfPrecision`. This PR implements that change, and closes issue #1068

Weight Validation Fix

---

schema/components.json
tests/definitions_test.py
tests/yaml_loader.py

- Introduce the usage of `decimal.Decimal` in order to catch inconsistencies with operations against floats in Python
- Created `DecimalSafeLoader` to deserialize YAML floats as `decimal.Decimal`
- Added file handler for `RefResolver` in order to also cast `decimal.Decimal` to floats loaded through a $ref.
Closes #1068

Fix float validation using decimal.Decimal

---

device-types/FS/FMU-MC042733.yaml

Create FS FMU-MC042733 CWDM Module as child object
Parent is: https://github.com/netbox-community/devicetype-library/blob/master/device-types/FS/FMU-1UFMX-N.yaml
Reference:
https://www.fs.com/products/42972.html

Create FS FMU-MC042733 CWDM Module

---

device-types/Dell/49H29.yaml
device-types/Dell/PowerVault_MD3200.yaml
device-types/Dell/PowerVault_ME4024.yml

The powervault me4024 is just a chassis that holds two controllers. as such it should be a parent child relationship with device bays

PowerVault ME4024 and 42H29 Controller

---

schema/components.json

Add type `other` for power ports, power outlets and interfaces to validation schema.
(Ref #1120)

Add power type other

---

device-types/HPE/Aruba-2530-24G.yaml

J9782A (2530-24) and J9776A(2530-24**G**) is different devices.
Modified values with referring to Quickspecs (https://support.hpe.com/hpesc/public/docDisplay?docId=emr_na-c03624915#N1040D)

Update Aruba 2530-24G

---

device-types/Datto/DSW100-24P-4X.yaml
device-types/Datto/DSW100-84P-4X.yaml
device-types/Datto/DSW100-8P-2G.yaml
device-types/Datto/DSW250-8P-2X.yaml

Current generation Datto switches use PoE Type `type2-ieee802.3az`

Update Datto Switch PoE to `type2-ieee802.3az`

---

device-types/Albis-Elcon/BIG2862.yaml
device-types/Albis-Elcon/BIG4862.yaml

Device used e.g. by German Telecom for their EC2.0 circuits

Add Albis-Elcon BIG 4862

---

tests/definitions_test.py

replace directory separator '/' with os.path.sep to be compatible linux/windows/macos

directory separator appropriate for exec env

---

device-types/Intel/NUC11TNHi5.yaml

Adding the Intel NUC device - used for network monitoring

Adding Intel NUC Model NUC11TNHi5 (Used for network monitoring)

---

module-types/Palo Alto/PAN-PWR-2200W-AC.yaml

This is the power supply for the Palo Alto PA-5450

Palo Alto PA-5450 Power Supply (PAN-PWR-2200W-AC)

---

device-types/Juniper/EX4100-24P.yaml
device-types/Juniper/EX4100-24T.yaml
device-types/Juniper/EX4100-48P.yaml
device-types/Juniper/EX4100-48T.yaml
module-types/Juniper/ex4100-fan-afi.yaml
module-types/Juniper/ex4100-fan-afo.yaml
module-types/Juniper/jpsu-150-ac-afi.yaml
module-types/Juniper/jpsu-150-ac-afo.yaml
module-types/Juniper/jpsu-150-dc-afo.yaml
module-types/Juniper/jpsu-920-ac-afo.yaml

These are based on the EX3400 device types.

Add Juniper EX4100 device types modified from EX3400 models

---

device-types/Thales/K6.yaml
device-types/Thales/T2000.yaml
module-types/Thales/YM-2301E.yaml
module-types/Thales/YM-2451C.yaml

Adding Thales/SafeNet/Gemalto Network HSMs and their PSUs
- Luna T7 (T2000)
- Luna K6

Thales/SafeNet Network HSMs

---

device-types/Cisco/ASA5506-X.yaml
device-types/Cisco/ASA5508-X.yaml
device-types/Cisco/ASA5516-X.yaml
device-types/Cisco/ASA5525-X.yaml

I noticed several Cisco ASA 5500 Series boxes had the wrong `is_full_depth` value. I verified with [Cisco's website](https://www.cisco.com/c/en/us/products/collateral/security/asa-firepower-services/datasheet-c78-742475.html) and updated the values

Update Cisco ASA 5500 series

---

device-types/Fortinet/FG-60E.yaml

According to the [spec sheet](https://www.allfirewalls.de/out/media/FG-60E_68a9f553ab0392c8e6347c8481b0cb13a4059ddc_FortiGate_FortiWiFi_60E_Series.pdf) the FGT-60E actually only has 7 internal ports (+3 DMZ/WAN Ports).
Additionally, the power port was given the wrong type. It is a DC terminal 12VDC port.

Fix wrong amount of interfaces for FGT-60E

---

module-types/Intel/XL710-QDA1.yaml

Add module-type for the Intel XL710 network card.
Based on: https://github.com/netbox-community/devicetype-library/blob/master/module-types/Intel/XL710-QDA2.yaml

adds Intel XL710-QDA1 network card module

---

device-types/FS/FMU-1UFMX-N.yaml
module-types/FS/FLG-PLC1x16LGX1LCA.yaml
module-types/FS/FLG-PLC1x2LGX1LCA.yaml
module-types/FS/FLG-PLC1x2LGX1SCA.yaml
module-types/FS/FLG-PLC1x4LGX1LCA.yaml
module-types/FS/FLG-PLC1x4LGX1SCA.yaml
module-types/FS/FLG-PLC1x8LGX1LCA.yaml
module-types/FS/FLG-PLC1x8LGX1SCA.yaml

Modules for LGX fiber splitter modules from FS
Fix the 1U enclosure - it actually has three bays, not two.
Add the LGX Cassette modules which go into the enclosure.
These are PON splitters and I couldn't find a better way of representing these in Netbox other than just defining them as patch panels.
Note, although the units themselves have a duplex connector for the "IN" port, only the top one is used for the splitter so I haven't added these as duplex.

FS LGX fiber splitter modules

---

device-types/Juniper/ACX2100-AC.yaml
device-types/Juniper/ACX2100-DC.yaml
device-types/Juniper/ACX2200-AC.yaml
device-types/Juniper/ACX2200-DC.yaml

Adding:
- ACX2100
- AC variant
- DC variant
- ACX2200
- AC variant
- DC variant
Some bits and pieces are missing from Juniper's documentation and the datasheet, however used the best available information from these and deployed hardware. Based the comments on the ports with interchangeable features on the ACX1100 which has already been added to the library.
[Hardware Guide - ACX2100](https://www.juniper.net/documentation/us/en/hardware/acx2000/index.html)
[Hardware Guide - ACX2200](https://www.juniper.net/documentation/us/en/hardware/acx2200/index.html)
[Datasheet](https://www.juniper.net/content/dam/www/assets/datasheets/us/en/routers/acx500-acx1000-acx2000-acx4000-universal-metro-routers-datasheet.pdf)

Add Juniper ACX2K series

---

device-types/Cisco/WS-C2960CG-8TC-L.yaml

The missing interface GigabitEthernet0/8 has been added to the template.

device-types/Cisco/WS-C2960CG-8TC-L.yaml: Add missing port

---

device-types/HP/t740.yaml
device-types/HPE/t740.yaml

Adding device-type for the HP t740 thin client (used as a router by me).
Inspired by: https://github.com/netbox-community/devicetype-library/blob/master/device-types/Intel/NUC11TNHi5.yaml

adding HP t740 thin client (used as router)

---

device-types/Cisco/WS-C3750G-24TS-S.yaml

Looks like height was accidentally set to 1.5U in commit 6f1fa04a7401e7ac321a9b54e2fb6c93f573fceb that was intended to implement half-height units.
My best guess is this device type was edited for test purposes and accidentally committed.
I've got this device in front of me and it's definitely 1U.

Fix height of WS-C3750G-24TS-S

---

device-types/Cisco/ASA5505.yaml

- Fix PoE attributes to be the correct format poe-mode --> poe_mode and poe-type --> poe_type

Update poe-mode and poe-type on CICSO ASA5505

---

README.md
device-types/QNAP/TS-873.yml

The documentation for the "position" attribute in README.md was misleading. This is what the documentation says:
> The module bay's position within the parent device
This isn't very clear, and it can easilly be interpreted as a physical description of where you can find the port. For example, this module bay definition that I found for the QNAP TS-873:
```yaml
module-bays:
- name: Slot 1
position: rear
- name: Slot 2
position: rear
```
This PR clears up the documentation for module bay positions to clarify what the position attribute is for, removes this spurious position definition, and attempts to teach users how the Automatic Component Renaming feature works, hopefully this will lead to better models.
(I've not done an exhaustive search for mis-use of the position attribute on module …

Improve documentation for module bay positions (and remove a spurious position)

---

requirements.txt
tests/definitions_test.py
tests/test_configuration.py

Updating pre-commit pytest script so that if `-a` or `--all-files` is called, it actually checks all files in the repository

Pre-Commit Update

---

device-types/HPE/456204-B21.yaml
device-types/HPE/571956-B21.yaml
device-types/HPE/638526-B21.yaml
device-types/HPE/BladeSystem-c7000.yaml
device-types/HPE/ProLiant-BL460c-Gen10.yaml
device-types/HPE/ProLiant-BL460c-Gen9.yaml
module-types/HPE/499253-B21.yaml
module-types/HPE/588603-B21.yaml

Hi!
Did some work to improve the BladeSystem c7000 modelling. The existing model did nothing to model interconnects nor onboard administrators, didn't model the PSU's as modular, and didn't model enclosure interlinks.
I'm sure there's some stuff that could be added with respect to weight and airflow information, but I think I already spent enough time modelling this EOL device, good enough to put it into our own docs. Hope it's useful to others as well!

Improve HPE BladeSystem c7000 modelling

---

tests/definitions_test.py
tests/device_types.py

As discovered in #1667 by @mihailim we have a missing test case (failure during test run) when a file is renamed to a valid name, but the slug and/or part number does not change. These changes implement checking for renamed files which should solve the issue

Pytest Test Case - Renamed File w/o Slug/PN Change

---

device-types/Fortinet/FG-1000D.yaml
device-types/Fortinet/FG-3200D.yaml
device-types/Fortinet/FG-500E.yaml
device-types/Fortinet/FG-600E.yaml

I have removed some information on the power supply ports because those fortigates have power supply bays and each power supply has its own part number.

Fortigate 3200D, 1000D and powersupply bays

---

device-types/TP-Link/OC200.yaml

Add the TP-Link OC200 hardware controller as a new device-type.
The device-type YAML has been tested via pre-commit.

Add TP-Link OC200 controller

---

device-types/Ubiquiti/UAP-AC-HD.yaml

Add the Ubiquiti UAP AC HD access point as a new device-type.
The device-type YAML has been tested via pre-commit.

Add Ubiquiti UAP AC HD access point

---

device-types/Dell/PowerConnect-7048P.yaml

Add the Dell PowerConnect 7048P switch as a new device-type.
The device-type YAML has been tested via pre-commit. It can also successfully be imported into the demo NetBox environment when copied and pasted as text. (This doesn’t seem to work when importing the uploaded file.)

Add Dell PowerConnect 7048P switch

---

device-types/Server Technology/C2WG24SN-YCLN5D6.yaml
device-types/Server Technology/C2XG24SN-YCLN5D6.yaml

Primary PDU has a console-server-port for "link".
Link PDU has a console-port for "link".
These ports can plug into one another and the Primary provides power over the RJ-12 cable to maintain power to the management board on the Link PDU in the event that the Link PDU loses mains.

add Server Technology PDUs

---

device-types/Fortinet/FG-90G.yaml
device-types/Fortinet/FS-108E-FPOE.yaml
device-types/Fortinet/FS-108E-POE.yaml
device-types/Fortinet/FS-108F-FPOE.yaml
device-types/Fortinet/FS-108F-POE.yaml
device-types/Fortinet/FS-108F.yaml
device-types/Fortinet/FS-124E-FPOE.yaml
device-types/Fortinet/FS-124E-POE.yaml
device-types/Fortinet/FS-124F-FPOE.yaml
device-types/Fortinet/FS-124F-POE.yaml
device-types/Fortinet/FS-248E-POE.yaml

Add device types:
- FortiGate 90G
- FortiSwitch 108E-FPOE
- FortiSwitch 108E-POE
- FortiSwitch 108F-FPOE
- FortiSwitch 108F-POE
- FortiSwitch 108F
- FortiSwitch 124E-FPOE
- FortiSwitch 124E-POE
- FortiSwitch 124F-FPOE
- FortiSwitch 124F-POE
- FortiSwitch 248E-POE

Add Fortinet devices (10 switches, 1 firewall)

---

device-types/Netgear/GSM7228PS.yaml
device-types/Netgear/GSM7228S.yaml
device-types/Netgear/GSM7252PS.yaml
device-types/Netgear/GSM7252S.yaml
device-types/Netgear/GSM7328FS.yaml
device-types/Netgear/GSM7328Sv1.yaml
device-types/Netgear/GSM7328Sv2.yaml
device-types/Netgear/GSM7352Sv1.yaml
device-types/Netgear/GSM7352Sv2.yaml

This includes the Netgear M5300 series of managed switches (24/48 port managed). If there's anything to change/update, drop me a note.
Unfortunately I have no images available, and while the manuals include proper front/back views of the devices, those likely conflict with this project's license, thus were not used.

Netgear M5300 series

---

schema/devicetype.json
schema/moduletype.json

I missed the commend after issue #1715 closed the first time.  The schema is the same as the one for `comment` so I'm not sure what kind of tests would be needed.

Updated JSON schema to allow `description`

---

device-types/WatchGuard/Firebox-M370.yaml
device-types/WatchGuard/Firebox-T80.yaml

Having to nearly identical manufacturer definitions which in the end result in the same slug value makes importing the whole list impossible.
This commit removes Watchguard and renames to manufacturer of both Firebox device types to WatchGuard.
This fixes issue #1970

renames Watchguard to WatchGuard

---

device-types/Fortinet/FG-1801F.yaml

- Add missing HA ports
- Fixed port speed SFP28 instead of SFP+
- Fixed port speed QSFP28 instead of QSFP
- Changed power supplies to modular
- Add link to Datasheet to comments
- Fixed name of mgmt2 port
- Add model FG-1801F

Fix wrong port types and add missing portsl, add FG-1801F

---

device-types/Panduit/FRME1.yaml
device-types/Panduit/FRME2.yaml
device-types/Panduit/FRME4.yaml
module-types/Panduit/FC29N-24-10AS.yaml
module-types/Panduit/FC29N-24-10U.yaml
module-types/Panduit/FC2XO-24-10AS.yaml
module-types/Panduit/FC2XO-24-10U.yaml

These Panduit 12x duplex LC MPO Cassettes have 2x MPO 12 fiber rear ports, not a single MPO 24 fiber.
All positions are duplex.
- https://www.panduit.com/en/products/fiber-optic-systems/fiber-optic-panels-cassettes-enclosures/fiber-optic-cassettes/fc2xo-24-10as.html
- https://www.panduit.com/en/products/fiber-optic-systems/fiber-optic-panels-cassettes-enclosures/fiber-optic-cassettes/fc2xo-24-10u.html
- https://www.panduit.com/en/products/fiber-optic-systems/fiber-optic-panels-cassettes-enclosures/fiber-optic-cassettes/fc29n-24-10as.html
- https://www.panduit.com/en/products/fiber-optic-systems/fiber-optic-panels-cassettes-enclosures/fiber-optic-cassettes/fc29n-24-10u.html

fix: multiple fixes on Panduit odf and cassettes

---

device-types/Juniper/ACX7024-AC.yaml
device-types/ZPE/NSR-BASE-DAC.yaml

The purpose of this PR is to replace legacy PR1955 which had binary files that were not required and should not have been committed.

MOD - adding ACX7024 Juniper device type and ZPE NSR

---

device-types/Mellanox/SX6012F-1BFS.yaml
device-types/Mellanox/SX6012F-1BRS.yaml
device-types/Mellanox/SX6012F-2BFS.yaml
device-types/Mellanox/SX6012F-2BRS.yaml
device-types/Mellanox/SX6012T-1BFS.yaml
device-types/Mellanox/SX6012T-2BFS.yaml

Add missing u_height field for child modules.
- Mellanox SX6012F-1BFS
- Mellanox SX6012F-1BRS
- Mellanox SX6012F-2BFS
- Mellanox SX6012F-2BRS
- Mellanox SX6012T-1BFS
- Mellanox SX6012T-2BFS
https://github.com/netbox-community/Device-Type-Library-Import/issues/123#issuecomment-2009982136

Fix missing u_height for Mellanox/SX6012*

---

device-types/Generic/ST-24-port-fiber-patch-panel-rear-splice.yaml

Rear port 18 was incorrectly named port 28. Causing the netbox-community/Device-Type-Library-Import to complain about the nonexistant port.
https://github.com/netbox-community/Device-Type-Library-Import/issues/123#issuecomment-2009982136

Incorrect rear_port ST-24-port-fiber-patch-panel-rear-splice

---

requirements.txt
schema/components.json
schema/devicetype.json
schema/generated_schema.json
schema/moduletype.json
schema/reusable.json
tests/definitions_test.py
tests/test_configuration.py

JSON Schema has deprecated the RefResolver that we have been relying on for validation. This is becoming even more prevalent as we update other test suites and python packages. This PR resolved the deprecation and also does the following:
- Updates jsonschema to 4.21.1
- Adds $id and #schema to each of the applicable schema files
- Updates schema references from file paths to URN's
- Adds new `SCHEMAS_BASEPATH` variable which defined the local path to the schema files

JSON Schema Migration

---

module-types/Intel/E810-2CQDA2.yaml
module-types/Intel/E810-CQDA1.yaml
module-types/Intel/E810-CQDA2.yaml
module-types/Intel/E810-CQDA2T.yaml
module-types/Intel/E810-XXVDA2.yaml
module-types/Intel/E810-XXVDA4.yaml
module-types/Intel/E810-XXVDA4T.yaml
module-types/Intel/I350-T2.yaml
module-types/Intel/I710-T4L.yaml
module-types/Intel/X520-DA1.yaml
module-types/Intel/X520-DA2.yaml
module-types/Intel/X540-T1.yaml
module-types/Intel/X540-T2.yaml
module-types/Intel/X550-T1.yaml
module-types/Intel/X550-T2.yaml
module-types/Intel/X710-DA2.yaml
module-types/Intel/X710-DA4.yaml
module-types/Intel/X710-T2L.yaml
module-types/Intel/X710-T4.yaml
module-types/Intel/X710-T4L.yaml
module-types/Intel/XL710-QDA1.yaml
module-types/Intel/XL710-QDA2.yaml
module-types/Intel/XXV710-DA1.yaml
module-types/Intel/XXV710-DA2.yaml
module-types/Intel/XXV710-DA2T.yaml

to the module library folder.
Alligned all interface naming to the method of "Ethernet/{module}/[1-4]"

Intel NICs: Add full series of Intel NICs

---

device-types/Cisco/N9K-C9332D-GX2B.yaml
device-types/Cisco/N9K-C9348D-GX2A.yaml
device-types/Cisco/N9K-C9364D-GX2A.yaml

Cisco Nexus 9300-GX2:
Model | Description
-- | --
Cisco Nexus 9364D-GX2A | 64 x 400-Gbps QSFP-DD and 2x 1/10 -Gbps SFP+ ports
Cisco Nexus 9348D-GX2A | 48 x 400-Gbps QSFP-DD and 2x 1/10 -Gbps SFP+ ports
Cisco Nexus 9332D-GX2B | 32 x 400-Gbps QSFP-DD and 2x 1/10 -Gbps SFP+ ports
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-743854.html

Cisco Nexus 9300-GX2

---

module-types/Cisco/NIM-16A.yaml

I'm adding the Module NIM-24A in PR #2131 with the weight.
I wanted to add weight to NIM-16A too since they are very similar modules and it makes sense for them to have the same fields. the only difference between them is the nim-24a has 8 more console server ports and weighs a bit more.

added the weight of NIM-16A

---

device-types/HPE/Virtual-Connect-SE-40Gb-F8-Module-for-Synergy.yaml

In this PR, I have added a single configuration file to define the Virtual Connect SE 40Gb F8 Module for HPE Synergy. While this product is marked as obsolete by HPE, it is still leveraged in active deployments.

Add Virtual Connect SE 40Gb F8 Module for Synergy

---

device-types/Fortinet/FG-400F.yaml

Hi, the 10gbase-x-sfpp Ports are not numbered as they were in the template. 
These Ports have they're own numbers (X1-X8). The last Ports then continue with the previous numbering, see attached image.
The old Port 17 would be a 10GE SFP+ Port. But the actual Port 17 on the Device is a 1GE SFP Port
Official datasheet with correct naming: https://www.fortinet.com/content/dam/fortinet/assets/data-sheets/fortigate-400f-series.pdf

Updated Port Names FG-400F.yaml

---

device-types/HPE/Aruba-6405-v2.yaml
device-types/HPE/Aruba-6405.yaml
device-types/HPE/Aruba-6410-v2.yaml
device-types/HPE/Aruba-6410.yaml

Fixed the position naming of the PSU and fan module bays
```
6410# show environment fan 
Fan tray information
------------------------------------------------------------------------------
Name  Description                           Status        Serial Number  Fans
------------------------------------------------------------------------------
1/1   R0X32A Aruba 6400 Fan Tray            ready         XXXXXXXXXX     4  
1/2   R0X32A Aruba 6400 Fan Tray            ready         XXXXXXXXXX     4  
1/3   R0X32A Aruba 6400 Fan Tray            ready         XXXXXXXXXX     4  
1/4   R0X32A Aruba 6400 Fan Tray            ready         XXXXXXXXXX     4  
```
```
6410# show environment power-supply 
------------------------------------------------------------------------------
Product  Serial …
```

Fix HPE Aruba 6400 module bay positions

---

device-types/Supermicro/AS-2124BT-HNTR.yaml
device-types/Supermicro/MBD-H12DST-B.yaml

Add Supermicro A+ Server 2124BT-HNTR and its servers' motherboard H12DST-B:
https://www.supermicro.com/en/Aplus/system/2U/2124/AS-2124BT-HNTR.cfm
https://www.supermicro.com/en/products/motherboard/H12DST-B
To-do: Add optional yet required SIOM cards for H12DST-B

Add Supermicro A+ Server 2124BT-HNTR and its servers' motherboard H12DST-B

---

device-types/Cisco/ASR-9006.yaml

There are duplicate positions, but it is on purpose, there is one count for management and one for line cards.
The interfaces are, for example:
first management module, RSP0:
Mg0/RSP**0**/CPU0/0
Mg0/RSP**0**/CPU0/1
second management module, RSP1:
Mg0/RSP**1**/CPU0/0
Mg0/RSP**1**/CPU0/1
first interface line card (with 10G ports), the module is in the second number
Te0/**0**/0/0
Te0/**0**/0/1
second line card (with 10G ports)
Te0/**1**/0/0
Te0/**1**/0/1

ASR-9006: add positions so modules get automatic components

---

device-types/TP-Link/TL-SG3424.yaml
device-types/TP-Link/TL-SG3424P.yaml

This pull request contains two commits with following changes:
- adding SG-3424, which is pretty much the same as SG-3424P (but without PoE)
- fixed SG-3424P power consumption

Added TP-Link SG-3424, power consumption fix for TP-Link SG-3424P

---

device-types/MikroTik/CCR1072-1G-8S-Plus.yaml
device-types/MikroTik/CCR2004-16G-2S-Plus.yaml
device-types/MikroTik/CCR2004-1G-12S-Plus-2XS.yaml
device-types/MikroTik/CCR2116-12G-4S-Plus.yaml
device-types/MikroTik/CCR2216-1G-12XS-2XQ.yaml
device-types/MikroTik/CRS320-8P-8B-4S-Plus-RM.yaml
device-types/MikroTik/CRS326-4C-Plus-20G-Plus-2Q-Plus-RM.yaml
device-types/MikroTik/CRS504-4XQ-IN.yaml
device-types/MikroTik/CRS510-8XS-2XQ-IN.yaml
device-types/MikroTik/CRS520-4XS-16XQ.yaml
module-types/MikroTik/12POW150.yaml
module-types/MikroTik/G1040A-60WF.yaml
module-types/MikroTik/G1483-0600WNB.yaml
module-types/MikroTik/MT-HotSwapFan.yaml
module-types/MikroTik/PW48V-12V150W.yaml

The udpated device definitions relate to the modules being added, where the devices uses swapable power supplies. And some swapable fan modules as well.
- Update CCR1072-1G-8S+
- Update CCR2004-16G-2S+
- Update CCR2216-1G-12XS-2XQ
- Add CRS320-8P-8B-4S+RM
- Add CRS326-4C+20G+2Q+RM
- Update CRS504-4XQ-IN
- Add CRS510-8XS-2XQ-IN
- Update CRS518-16XS-2XQ
- Add CRS520-4XS-16XQ
Add additional Power Modules and Fans for module bays
- Add 12POW150
- Add G1040-60WF
- Add G1483-0600WNB
- Add MT-HotSwapFan
- Add PW48V-12POW150

Add MikroTik CRS520-4XS-16XQ, CRS510-8XS-2XQ-IN, CRS320-8P-8B-4S+RM, CRS326-4C+20G+2Q+RM & 5 MikroTik module-types

---

module-types/Cisco/N55-M16P.yaml

Create N55-M16P module used in Nexus switches (Nexus 5548UP for example).

Create N55-M16P module used in Nexus switches

---

device-types/Cuda/WR3000-v1.yaml

Adds device type for Cudy WR3000 v1 Wifi access point.

New Device type: Cudy WR3000 v1

---

device-types/AVM/FRITZBox-7690.yaml

I named the combo WAN/LAN port `WAN_LAN` as I couldn't figure out syntax of valid names (I'm a new NetBox user)

Add FRITZ!Box 7690

---

device-types/Extreme Networks/X150-24p.yaml
device-types/Extreme Networks/X150-24t.yaml
device-types/Extreme Networks/X150-48t.yaml
tests/definitions_test.py

This commit addresses the issue #2461 by updating the test case to detect non-ASCII characters in YAML files. The new check ensures that if any non-ASCII characters are found, the test will fail and provide a clear message listing the problematic characters.
•	Added a check to identify non-ASCII characters in the content of the YAML files.
•	If non-ASCII characters are found, the test will now fail with a detailed error message, including the list of non-ASCII characters.
This update helps ensure that YAML files are strictly ASCII-encoded, avoiding potential encoding issues in different environments.

Fix: Prevent non ascii characters in yaml files issue #2461

---

device-types/D-Link/DWS-3160-24TC.yaml

Added DWS-3160-24TC
Official specs: https://www.dlink.com/uk/en/products/dws-3160-series-gigabit-l2plus-unified-managed-switches

D link dws 3160 24tc

---

device-types/Minisforum/Minisforum-MS-01.yml

Fix: Remove rear-port declarations from Minisforum MS-01 (#2709)

---

device-types/Bachmann/Bachmann-107686.yaml

Bachmann is an independent vendor, I mistakenly thought they were part of Max Hauri. 
Moving device-type into the correct vendor directory.

Move Bachmann-107686 device to correct vendor directory

---

module-types/Cisco/UCSX-9508-FAN.yaml
module-types/Cisco/UCSX-9508-RBLK.yaml
module-types/Cisco/UCSX-I-9108-100G.yaml
module-types/Cisco/UCSX-PSU-2800AC.yaml

The Cisco UCS-X 9508 chassis has module slots defined, but no modules.  This PR adds some of them to the repo.

Add module types for Cisco UCS-X 9508 chassis

---

device-types/Cisco/C6807-XL.yaml
module-types/Cisco/VS-S2T-10G.yaml
module-types/Cisco/WS-X6904-40G.yaml

C6807-XL and VS-S2T-10G should be self-explanatory, but regarding WS-X6904-40G, there are three possible setups depending on the transceiver used:
- 4 40GE ports
- 16 10GE ports
- Mixed 40GE/10GE ports
I'm not sure how to properly handle this, but seeing precedent from [FWB-2000E](https://github.com/netbox-community/devicetype-library/blob/1b261daa6bb33a28dc663c4042b090c9ed597116/device-types/Fortinet/FWB-2000E.yaml#L35), I decided to use this approach. I put the interfaces and numbers in the appropriate position (e.g. if it's 40G then the if number is Fo{module}/1, but if it's 10G ten they'll be Te{module}/[5-8] and so on, see datasheet for more info).

Cisco: Modify C6807-XL and add 2 different modules

---

device-types/Supermicro/SYS-221H-TNR.yaml
module-types/Supermicro/AOC-ATG-i2TM.yaml
module-types/Supermicro/PWS-1K63A-1R.yaml

- Device: <https://www.supermicro.com/en/products/system/hyper/2u/sys-221h-tnr>
- [NOTE] As described in "Expansion Slots" section, This server has a choice of PCIe expansion slot options A or B. The yaml of this PR is written based on option A (4 PCIe 5.0 x16 FH/10.5"L double-width slots) for now. Therefore, please note that some PCI slot numbers appear to be skipped.
- Related Modules
- PSU: <https://store.supermicro.com/us_en/1600w-1u-pws-1k63a-1r.html> 
- AIOM NIC: <https://www.supermicro.com/en/products/accessories/addon/AOC-ATG-i2T.php>

Add Supermicro SuperServer SYS-221H-TNR device-type and some related module-types

---

module-types/Cisco/N9K-X9788TC-FX.yaml

The N9K-X9788TC-FX had the wrong interface type/count
As this module is a 48x10G + 4x100G module, this fixes the port count and change the port type to 10gbase-t for the first 48 ports.

fix N9K-X9788TC-FX linecard with 10gbase-t ports

---

device-types/Cisco/N9K-C93108TC-EX.yaml

added missing weight for Cisco N9K-C93108TC-EX (without fans, without PSUs)

added N9K-C93108TC-EX weight

---

device-types/FS/FMU-1UFMX-N.yaml

The device only has two bays:
https://www.fs.com/de/products/30408.html?now_cid=1202

Update FMU-1UFMX-N - Correct device bays

---

module-types/Cisco/C9400-LC-24XS.yaml
module-types/Cisco/C9400-LC-48S.yaml
module-types/Cisco/C9400-LC-48U.yaml
module-types/Cisco/C9400-LC-48UX.yaml
module-types/Cisco/C9400-LC-48XS.yaml
module-types/Cisco/C9400-PWR-2100AC.yaml
module-types/Cisco/C9400-PWR-3200AC.yaml
module-types/Cisco/C9400-SUP-1.yaml
module-types/Cisco/C9400-SUP-1XL-Y.yaml

Add weight data to Cisco Catalyst 9400 Series modules.
Also split existing comment into `description` and `comments` fields to improve clarity and maintain consistency with other module entries.
Source: [Cisco Catalyst 9400 Series Switches Hardware Installation Guide](https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9400/hardware/install/b_c9400_hig/b_c9400_hig_chapter_0110.html)

Add weight to Cisco Catalyst 9400 modules

---

module-types/Cisco/C9400-LC-48HN.yaml
module-types/Cisco/C9400-LC-48HX.yaml
module-types/Cisco/C9400X-SUP-2.yaml
module-types/Cisco/C9400X-SUP-2XL.yaml
module-types/Cisco/C9404-FAN.yaml
module-types/Cisco/C9407-FAN.yaml
module-types/Cisco/C9410-FAN.yaml

Add support for the following Cisco Catalyst 9400 Series modules:
- C9400-LC-48HN
- C9400-LC-48HX
- C9400X-SUP-2
- C9400X-SUP-2XL
- C9404-FAN
- C9407-FAN
- C9410-FAN
These modules include supervisor engines, line cards, and fan trays, enhancing coverage of the Catalyst 9400 Series in the device type library.

Add new Cisco Catalyst 9400 Series modules

---

module-types/HPE/865414-B21.yaml

I have checked the **HPE 800W Flex Slot Platinum Hot Plug Low Halogen Power Supply Kit** module definition, and found some updates for that module. See official [hardware specs](https://www.hpe.com/psnow/doc/PSN1009449980BEEN.pdf)
Changes implemented:
- added `weight` and `weight_unit`
- corrected typo in maximum power draw from `899` to `800`
- corrected markdown link in the comment - missing brackets and updated the link to the specific document for that module

HPE 865414 b21 (HPE 800W power supply module) update comment, power draw and weight

---

device-types/Generic/shelf-1he-full-depth.yaml
device-types/Supermicro/SYS-5019S-M.yaml
device-types/Supermicro/SYS-6028TR-HTR.yaml
device-types/Supermicro/SYS-6029U-TR4T+.yaml
device-types/Supermicro/SuperChassis-826-BE1C4.yaml
device-types/Ubiquiti/ER-8-XG.yaml

Add new devices for:
- Ubiquiti EdgeRouter Infinity, their 10GbE 1U version
- Supermicro Superserver 6028U-TR4T+
- Supermicro SuperServer 6028TR-HTR (4-node system)
- SuperChassis 826BE1C4 (empty chassis)
- Supermicro SuperServer 5019S-M (1U system)
... plus a full-depth version of a generic 1U shelf.

Add a handful of new devices

---

device-types/APC/SMT1000RMI2UC.yaml

Please add APC SMT1000RMI2UC to device type library.
Link to specs: https://www.se.com/de/de/product/SMT1000RMI2UC/apc-smartups-line-interactive-1000va-rackmontage-2he-230v-4-iec-c13stecker-smartconnect-port+smartslot-avr-lcd/
Thank you.

Please add APC SMT1000RMI2UC to device type library

---

module-types/HPE/500172-B21.yaml
module-types/HPE/503296-B21.yaml
module-types/HPE/512327-B21.yaml
module-types/HPE/578322-B21.yaml
module-types/HPE/656362-B21.yaml
module-types/HPE/656363-B21.yaml
module-types/HPE/656364-B21.yaml
module-types/HPE/684532-B21.yaml
module-types/HPE/697581-B21.yaml
module-types/HPE/739252-B21.yaml
module-types/HPE/739254-B21.yaml
module-types/HPE/748287-B21.yaml

Introduces all possible AC powered common slot power supplies for various HPE ProLiant G6, G7 and Gen8 servers

Addition of all AC common slot PSUs for HPE ProLiant G6, G7 and Gen8

---

device-types/HPE/ProLiant-DL380-Gen11.yaml
device-types/HPE/ProLiant-DL385-Gen11.yaml

Update modules and interfaces on ProLiant-DL380-Gen11
Remove FlexLOM
Add OCP3.0 modules
Remove Gigabit interfaces
Update modules for ProLiant-DL385-Gen11
Add both OCP3 ports 
Add tertiary riser
Add DB-9 port

Fix HPE dl38x gen11 servers

---

device-types/Huawei/CE6865-48S8CQ-EI.yaml

Huawei CloudEngine 6865, 48x25GE, 8x100GE
Link: https://support.huawei.com/enterprise/en/doc/EDOC1000019246/3082bcde/ce6865-48s8cq-ei
Link: https://info.support.huawei.com/info-finder/vue/search-center/en/enterprise/routers/ce6800-pid-C00000000059/hardwarecenter?keyword=02351RFC&productModel=CE6865-48S8CQ-EI#specifacations
This device __does not__ have a fixed air flow direction, so `airflow` is not specified. The direction of air flow is determined by the fan modules installed.

Add CE6865-48S8CQ-EI.yaml

---

module-types/HPE/P65741-B21.yaml

iLO kit for new HPE Proliant Microserver Gen11 boxes.
Also has M.2 bay, but not sure if adding that is better handled by "disks" tab in device.

Add HPE P65741-B21 iLO enablement kit.

---

device-types/Cisco/NCS-6008.yaml

The NCS-6008 does not allow the insertion of an RSP, but allows the insertion of an RP.

Update NCS-6008.yaml, from RSP to RP.

---

device-types/Juniper/SRX1600.yaml

This PR fixes the port names for the Juniper SRX1600 to match the [documentation](https://www.juniper.net/documentation//us/en/software/junos/interfaces-security-devices/topics/topic-map/port-speed-srx-firewalls.html#concept_igk_dsh_vcc__d146e185).

fix Juniper SRX1600 port names
